// Asset database source: one row per token PNG.
// Sheet blocks carry defaults (side/faction/role/base); per-unit entry = [id, ko, en, {overrides}].
// side: good | evil | terrain   role: hero | infantry | cavalry | monster | support | terrain
// base: S | M | L | XL | XXL   weapon: sword|sword_shield|spear|spear_shield|bow|crossbow|pike|twohanded|axe|mace|club|staff|banner|drum|dagger|bomb|torch|pitchfork|none|various
module.exports = [
{ sheet: 'lotr-tokens-v1.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['aragorn', '아라곤', 'Aragorn'],
  ['gandalf', '간달프', 'Gandalf the Grey', { faction: 'maiar', weapon: 'staff' }],
  ['warrior_minas_tirith', '미나스 티리스 전사', 'Warrior of Minas Tirith', { role: 'infantry', weapon: 'sword_shield', base: 'M' }],
  ['witchking_foot', '마술왕(도보)', 'Witch-king on foot', { side: 'evil', faction: 'angmar', weapon: 'sword' }],
  ['orc_sword', '모르도르 오크(검)', 'Mordor Orc, sword', { side: 'evil', faction: 'mordor', role: 'infantry', base: 'S' }],
  ['cave_troll', '동굴 트롤', 'Cave Troll', { side: 'evil', faction: 'moria', role: 'monster', weapon: 'club', base: 'XXL' }],
]},
{ sheet: 'glorfindel-topdown-v2.png', side: 'good', faction: 'rivendell', role: 'hero', weapon: 'sword', units: [
  ['glorfindel_foot', '글로르핀델(도보)', 'Glorfindel on foot', { base: 'L' }],
  ['glorfindel_mounted', '글로르핀델(기마)', 'Glorfindel mounted', { role: 'cavalry', base: 'XL' }],
]},
{ sheet: 'fellbeast-topdown-v2.png', side: 'evil', faction: 'angmar', role: 'monster', base: 'XXL', units: [
  ['witchking_fellbeast', '마술왕(펠비스트)', 'Witch-king on Fell Beast', { weapon: 'sword' }],
]},
{ sheet: 'witchking-mounted-topdown-v1.png', side: 'evil', faction: 'angmar', role: 'cavalry', weapon: 'sword', base: 'XL', units: [
  ['witchking_mounted', '마술왕(기마)', 'Witch-king mounted'],
]},
{ sheet: 'roster-enemy-heroes-v1.png', side: 'evil', faction: 'mordor', role: 'hero', weapon: 'sword', units: [
  ['witchking_mounted_sheet', '마술왕(기마·예비)', 'Witch-king mounted (alt)', { faction: 'angmar', role: 'cavalry', base: 'XL' }],
  ['witchking_foot_mace', '마술왕(철퇴)', 'Witch-king with mace', { faction: 'angmar', weapon: 'mace', base: 'L' }],
  ['nazgul_sword', '나즈굴(검)', 'Nazgul, sword', { faction: 'angmar', base: 'L' }],
  ['saruman', '사루만', 'Saruman the White', { faction: 'isengard', weapon: 'staff', base: 'L' }],
  ['orc_shaman', '오크 주술사', 'Orc Shaman', { faction: 'moria', role: 'support', weapon: 'staff', base: 'S' }],
  ['orc_captain', '오크 대장', 'Orc Captain', { base: 'M' }],
]},
{ sheet: 'roster-enemy-troops-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'S', units: [
  ['orc_spearman', '오크 창병', 'Orc Spearman', { weapon: 'spear' }],
  ['orc_archer', '오크 궁수', 'Orc Archer', { weapon: 'bow' }],
  ['uruk_swordshield', '우르크하이 검방', 'Uruk-hai, sword & shield', { faction: 'isengard', weapon: 'sword_shield', base: 'M' }],
  ['morannon_orc', '모라논 오크', 'Morannon Orc', { weapon: 'spear_shield', base: 'M' }],
  ['warg_rider', '와르그 기병', 'Warg Rider', { role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['haradrim_spearman', '하라드림 창병', 'Haradrim Spearman', { faction: 'harad', weapon: 'spear', base: 'M' }],
]},
{ sheet: 'roster-free-heroes-v1.png', side: 'good', role: 'hero', weapon: 'sword', units: [
  ['legolas', '레골라스', 'Legolas', { faction: 'elf', weapon: 'bow', base: 'M' }],
  ['gimli', '김리', 'Gimli', { faction: 'dwarf', weapon: 'axe', base: 'M' }],
  ['boromir', '보로미르', 'Boromir', { faction: 'gondor', weapon: 'sword_shield', base: 'L' }],
  ['eowyn', '에오윈', 'Eowyn', { faction: 'rohan', weapon: 'sword', base: 'M' }],
  ['frodo', '프로도', 'Frodo', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['elrond', '엘론드', 'Elrond', { faction: 'rivendell', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-free-troops-v1.png', side: 'good', role: 'infantry', base: 'M', units: [
  ['gondor_archer', '곤도르 궁수', 'Gondor Archer', { faction: 'gondor', weapon: 'bow' }],
  ['elf_swordsman', '엘프 검사', 'Elf Swordsman', { faction: 'elf', weapon: 'sword' }],
  ['dwarf_guardian', '드워프 가디언', 'Dwarf Guardian', { faction: 'dwarf', weapon: 'axe' }],
  ['rohan_royal_guard', '로한 근위병', 'Rohan Royal Guard', { faction: 'rohan', weapon: 'spear_shield' }],
  ['ithilien_ranger', '이틸리엔 레인저', 'Ithilien Ranger', { faction: 'gondor', weapon: 'bow' }],
  ['rohan_rider', '로한 기병', 'Rider of Rohan', { faction: 'rohan', role: 'cavalry', weapon: 'spear', base: 'XL' }],
]},
{ sheet: 'roster-monsters-v1.png', side: 'evil', role: 'monster', base: 'XXL', weapon: 'various', units: [
  ['balrog', '발록', 'Balrog of Moria', { faction: 'moria' }],
  ['mountain_troll', '산악 트롤', 'Mountain Troll', { faction: 'mordor', weapon: 'club' }],
  ['shelob', '셀로브', 'Shelob', { faction: 'mordor' }],
  ['barrow_wight', '고분 망령', 'Barrow-wight', { faction: 'angmar', role: 'hero', weapon: 'sword', base: 'M' }],
  ['moria_goblin', '모리아 고블린', 'Moria Goblin', { faction: 'moria', role: 'infantry', weapon: 'sword', base: 'S' }],
  ['uruk_berserker', '우르크 광전사', 'Uruk-hai Berserker', { faction: 'isengard', role: 'infantry', weapon: 'twohanded', base: 'M' }],
]},
{ sheet: 'roster-sauron-nazgul-v1.png', side: 'evil', role: 'hero', base: 'L', units: [
  ['sauron', '사우론', 'Sauron', { faction: 'mordor', weapon: 'mace', base: 'XXL' }],
  ['nazgul_sword_2', '나즈굴(검·B)', 'Nazgul, sword (v2)', { faction: 'angmar', weapon: 'sword' }],
  ['nazgul_mace', '나즈굴(철퇴)', 'Nazgul, mace', { faction: 'angmar', weapon: 'mace' }],
  ['nazgul_mounted', '나즈굴(기마)', 'Nazgul mounted', { faction: 'angmar', role: 'cavalry', weapon: 'sword', base: 'XL' }],
  ['morgul_knight', '모르굴 기사', 'Morgul Knight', { faction: 'mordor', role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['dwimmerlaik', '드위머레이크(갑옷 나즈굴)', 'Dwimmerlaik', { faction: 'angmar', weapon: 'mace' }],
]},
{ sheet: 'roster-minastirith-variants-v1.png', side: 'good', faction: 'gondor', role: 'infantry', base: 'M', units: [
  ['mt_swordshield', '미나스 티리스 검방', 'MT sword & shield', { weapon: 'sword_shield' }],
  ['mt_spear', '미나스 티리스 창병', 'MT spear', { weapon: 'spear' }],
  ['mt_spearshield', '미나스 티리스 창방', 'MT spear & shield', { weapon: 'spear_shield' }],
  ['mt_bowman', '미나스 티리스 궁수', 'MT bowman', { weapon: 'bow' }],
  ['mt_captain', '미나스 티리스 장교', 'MT shield captain'],
  ['mt_fountain_guard', '샘물수위병', 'Fountain Court Guard', { weapon: 'spear_shield' }],
]},
{ sheet: 'roster-orc-variants-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'S', units: [
  ['orc_sword2', '오크(검)', 'Orc, sword', { weapon: 'sword' }],
  ['orc_swordshield', '오크(검방)', 'Orc, sword & shield', { weapon: 'sword_shield' }],
  ['orc_spear2', '오크(창)', 'Orc, spear', { weapon: 'spear' }],
  ['orc_twohanded', '오크(양손도끼)', 'Orc, two-handed axe', { weapon: 'twohanded' }],
  ['orc_bow', '오크(활)', 'Orc, bow', { weapon: 'bow' }],
  ['orc_drummer', '오크 전쟁북', 'Orc war drummer', { role: 'support', weapon: 'drum' }],
]},
{ sheet: 'roster-dwarf-variants-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['dwarf_axeshield', '드워프 도끼방', 'Dwarf, axe & shield', { weapon: 'axe' }],
  ['dwarf_2haxe', '드워프 양손도끼', 'Dwarf, two-handed axe', { weapon: 'twohanded' }],
  ['dwarf_ranger', '드워프 레인저', 'Dwarf Ranger', { weapon: 'bow' }],
  ['khazad_guard', '카자드 근위병', 'Khazad Guard', { weapon: 'axe' }],
  ['iron_guard', '아이언 가드', 'Iron Guard', { weapon: 'sword_shield' }],
  ['dwarf_banner', '드워프 기수', 'Dwarf banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-elf-variants-v1.png', side: 'good', faction: 'elf', role: 'infantry', base: 'M', units: [
  ['elf_swordshield', '엘프 검방', 'Elf, sword & shield', { weapon: 'sword_shield' }],
  ['elf_spear', '엘프 창병', 'Elf, spear', { weapon: 'spear' }],
  ['elf_bow', '엘프 궁수', 'Elf, bow', { weapon: 'bow' }],
  ['elf_glaive', '엘프 글레이브', 'Elf, glaive', { weapon: 'twohanded' }],
  ['galadhrim_warrior', '갈라드림 전사', 'Galadhrim Warrior', { faction: 'lothlorien', weapon: 'sword' }],
  ['elf_knight', '엘프 기마기사', 'Elf Knight', { faction: 'rivendell', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-uruk-variants-v1.png', side: 'evil', faction: 'isengard', role: 'infantry', base: 'M', units: [
  ['uruk_swordshield2', '우르크하이 검방', 'Uruk-hai, sword & shield', { weapon: 'sword_shield' }],
  ['uruk_pike', '우르크하이 파이크', 'Uruk-hai, pike', { weapon: 'pike' }],
  ['uruk_crossbow', '우르크하이 석궁', 'Uruk-hai, crossbow', { weapon: 'crossbow' }],
  ['uruk_scout', '우르크하이 스카웃', 'Uruk-hai Scout', { weapon: 'sword' }],
  ['uruk_berserker2', '우르크하이 광전사', 'Uruk-hai Berserker', { weapon: 'twohanded' }],
  ['uruk_banner', '우르크하이 기수', 'Uruk-hai banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-haradrim-easterling-v1.png', side: 'evil', role: 'infantry', base: 'M', units: [
  ['haradrim_spear', '하라드림 창병', 'Haradrim spearman', { faction: 'harad', weapon: 'spear' }],
  ['haradrim_bow', '하라드림 궁수', 'Haradrim archer', { faction: 'harad', weapon: 'bow' }],
  ['haradrim_priest', '하라드림 전사제', 'Haradrim warrior priest', { faction: 'harad', role: 'support', weapon: 'staff' }],
  ['easterling_phalanx', '이스터링 방진병', 'Easterling phalangite', { faction: 'easterling', weapon: 'pike' }],
  ['easterling_swordshield', '이스터링 검방', 'Easterling, sword & shield', { faction: 'easterling', weapon: 'sword_shield' }],
  ['easterling_kataphrakt', '이스터링 중기병', 'Easterling Kataphrakt', { faction: 'easterling', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-gondor-exp-v1.png', side: 'good', faction: 'gondor', role: 'infantry', base: 'M', units: [
  ['dol_amroth_knight', '돌 암로스 백조기사', 'Knight of Dol Amroth', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['gondor_knight', '곤도르 기병', 'Knight of Minas Tirith', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['osgiliath_veteran', '오스길리아스 베테랑', 'Osgiliath Veteran', { weapon: 'sword_shield' }],
  ['lossarnach_axeman', '로사르나흐 도끼병', 'Lossarnach Axeman', { weapon: 'twohanded' }],
  ['citadel_guard', '성채근위병', 'Citadel Guard', { weapon: 'spear_shield' }],
  ['pelennor_militia', '펠렌노르 민병', 'Pelennor Militia', { weapon: 'spear' }],
]},
{ sheet: 'roster-rohan-exp-v1.png', side: 'good', faction: 'rohan', role: 'infantry', base: 'M', units: [
  ['rohan_swordshield', '로한 검방', 'Rohan, sword & shield', { weapon: 'sword_shield' }],
  ['rohan_spear', '로한 창병', 'Rohan, spear', { weapon: 'spear' }],
  ['rohan_archer', '로한 궁수', 'Rohan archer', { weapon: 'bow' }],
  ['eomer', '에오메르(기마)', 'Eomer mounted', { role: 'hero', weapon: 'sword', base: 'XL' }],
  ['rohan_outrider', '로한 기마궁수', 'Rohan outrider', { role: 'cavalry', weapon: 'bow', base: 'XL' }],
  ['rohan_banner', '로한 기수', 'Rohan banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-mordor-elite-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'M', units: [
  ['black_numenorean', '검은 누메노르인(도보)', 'Black Numenorean on foot', { weapon: 'sword_shield' }],
  ['black_numenorean_mounted', '검은 누메노르인(기마)', 'Black Numenorean mounted', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['orc_tracker', '오크 추적자', 'Orc Tracker', { weapon: 'twohanded', base: 'S' }],
  ['war_troll', '전쟁 트롤', 'Mordor War Troll', { role: 'monster', weapon: 'club', base: 'XXL' }],
  ['black_guard', '바라드두르 흑근위', 'Black Guard of Barad-dur', { weapon: 'spear_shield' }],
  ['orc_taskmaster', '오크 두목', 'Orc Taskmaster', { role: 'support', weapon: 'whip' }],
]},
{ sheet: 'roster-goblin-v1.png', side: 'evil', faction: 'moria', role: 'infantry', base: 'S', units: [
  ['goblin_spear', '고블린 창병', 'Goblin, spear', { weapon: 'spear' }],
  ['goblin_shield', '고블린 방패병', 'Goblin, shield', { weapon: 'sword_shield' }],
  ['goblin_bow', '고블린 궁수', 'Goblin, bow', { weapon: 'bow' }],
  ['goblin_prowler', '고블린 프라울러', 'Goblin Prowler', { weapon: 'dagger' }],
  ['goblin_king', '고블린 왕', 'Goblin King', { role: 'hero', weapon: 'club', base: 'L' }],
  ['goblin_shaman', '고블린 샤먼', 'Goblin Shaman', { role: 'support', weapon: 'staff' }],
]},
{ sheet: 'roster-isengard-exp-v1.png', side: 'evil', role: 'infantry', base: 'M', units: [
  ['dunlending_warrior', '던랜딩 전사', 'Dunlending Warrior', { faction: 'dunland', weapon: 'sword' }],
  ['dunlending_huscarl', '던랜딩 허스칼', 'Dunlending Huscarl', { faction: 'dunland', weapon: 'twohanded' }],
  ['warg', '야생 와르그', 'Wild Warg', { faction: 'isengard', role: 'monster', weapon: 'none' }],
  ['uruk_sapper', '우르크 폭파반', 'Uruk-hai Demolition Team', { faction: 'isengard', weapon: 'bomb' }],
  ['uruk_scout_archer', '우르크 스카웃 궁수', 'Uruk-hai Scout Archer', { faction: 'isengard', weapon: 'bow' }],
  ['crebain_swarm', '크레반 까마귀 떼', 'Crebain swarm', { faction: 'isengard', role: 'support', weapon: 'none' }],
]},
{ sheet: 'roster-free-special-v1.png', side: 'good', base: 'M', units: [
  ['hobbit_shirriff', '호빗 민병', 'Hobbit Shirriff', { faction: 'shire', role: 'infantry', weapon: 'pitchfork', base: 'S' }],
  ['hobbit_bounder', '호빗 궁수', 'Hobbit Bounder', { faction: 'shire', role: 'infantry', weapon: 'bow', base: 'S' }],
  ['great_eagle', '대독수리', 'Great Eagle', { faction: 'eagle', role: 'monster', weapon: 'none', base: 'XL' }],
  ['ent', '엔트', 'Ent', { faction: 'ent', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['beorning', '베오르닝 전사', 'Beorning', { faction: 'beorning', role: 'hero', weapon: 'axe', base: 'L' }],
  ['ranger_north', '북부 레인저', 'Ranger of the North', { faction: 'arnor', role: 'infantry', weapon: 'sword' }],
]},
{ sheet: 'roster-free-heroes-exp-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['theoden', '세오덴(기마)', 'Theoden mounted', { faction: 'rohan', role: 'cavalry', weapon: 'sword_shield', base: 'XL' }],
  ['faramir', '파라미르', 'Faramir', { faction: 'gondor', weapon: 'bow' }],
  ['haldir', '할디르', 'Haldir', { faction: 'lothlorien', weapon: 'twohanded' }],
  ['galadriel', '갈라드리엘', 'Galadriel', { faction: 'lothlorien', weapon: 'none' }],
  ['gamling', '감링(기수)', 'Gamling with banner', { faction: 'rohan', weapon: 'banner' }],
  ['samwise', '샘와이즈', 'Samwise Gamgee', { faction: 'shire', weapon: 'dagger', base: 'S' }],
]},
{ sheet: 'roster-evil-heroes-exp-v1.png', side: 'evil', role: 'hero', units: [
  ['mouth_of_sauron', '사우론의 입(기마)', 'Mouth of Sauron', { faction: 'mordor', role: 'cavalry', weapon: 'sword', base: 'XL' }],
  ['gothmog', '고스모그', 'Gothmog', { faction: 'mordor', weapon: 'mace', base: 'L' }],
  ['lurtz', '루르츠', 'Lurtz', { faction: 'isengard', weapon: 'bow', base: 'M' }],
  ['sharku', '샤르쿠(와르그)', 'Sharku on warg', { faction: 'isengard', role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['grima', '그리마 웜텅', 'Grima Wormtongue', { faction: 'isengard', weapon: 'dagger', base: 'M' }],
  ['khamul', '카물', 'Khamul the Easterling', { faction: 'angmar', weapon: 'mace', base: 'L' }],
]},
{ sheet: 'roster-legends-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['fingolfin', '핑골핀', 'Fingolfin', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['imrahil', '임라힐', 'Imrahil', { faction: 'gondor', weapon: 'lance' }],
  ['merry', '메리아독', 'Meriadoc Brandybuck', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['pippin', '피핀', 'Peregrin Took', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['beorn', '베오른', 'Beorn', { faction: 'beorning', weapon: 'twohanded', base: 'L' }],
  ['elendil', '엘렌딜', 'Elendil', { faction: 'arnor', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-legends-evil-v1.png', side: 'evil', units: [
  ['melkor', '멜코르', 'Melkor (Morgoth)', { faction: 'angband', role: 'monster', weapon: 'mace', base: 'XXL' }],
  ['mumakil', '무마킬', 'War Mumak', { faction: 'harad', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['smaug', '스마우그', 'Smaug', { faction: 'erebor', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['ungoliant', '웅골리안트', 'Ungoliant', { faction: 'angband', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['bolg', '볼그', 'Bolg', { faction: 'gundabad', role: 'hero', weapon: 'mace', base: 'L' }],
  ['easterling_warlord', '이스터링 장군', 'Easterling Warlord', { faction: 'easterling', role: 'hero', weapon: 'pike' }],
]},
{ sheet: 'roster-legends-good-v2.png', side: 'good', role: 'hero', base: 'M', units: [
  ['radagast', '라다가스트', 'Radagast the Brown', { faction: 'maiar', weapon: 'staff' }],
  ['thranduil', '트란두일', 'Thranduil', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['celeborn', '켈레보른', 'Celeborn', { faction: 'lothlorien', weapon: 'spear' }],
  ['bilbo', '빌보', 'Bilbo Baggins', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['king_of_the_dead', '망자의 왕', 'King of the Dead', { faction: 'dead', weapon: 'sword', base: 'L' }],
  ['dead_soldier', '망자 병사', 'Soldier of the Dead', { faction: 'dead', role: 'infantry', weapon: 'spear' }],
]},
{ sheet: 'roster-legends-evil-v2.png', side: 'evil', units: [
  ['olog_hai', '올로그하이', 'Olog-hai', { faction: 'mordor', role: 'monster', weapon: 'mace', base: 'XXL' }],
  ['watcher_in_the_water', '물 속의 감시자', 'Watcher in the Water', { faction: 'moria', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['mirkwood_spider', '미르크우드 거미', 'Mirkwood Spider', { faction: 'dol_guldur', role: 'monster', weapon: 'none', base: 'L' }],
  ['harad_chieftain', '하라드 족장', 'Haradrim Chieftain', { faction: 'harad', role: 'hero', weapon: 'sword' }],
  ['uruk_captain', '우룩하이 대장', 'Uruk-hai Captain', { faction: 'isengard', role: 'hero', weapon: 'sword_shield', base: 'L' }],
  ['hill_troll', '언덕 트롤', 'Hill Troll', { faction: 'angmar', role: 'monster', weapon: 'club', base: 'XL' }],
]},
{ sheet: 'roster-silmarillion-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['feanor', '페아노르', 'Feanor', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['luthien', '루시엔', 'Luthien', { faction: 'doriath', weapon: 'staff' }],
  ['beren', '베렌', 'Beren', { faction: 'men', weapon: 'sword' }],
  ['turin', '투린', 'Turin Turambar', { faction: 'men', weapon: 'sword', base: 'L' }],
  ['beleg', '벨레그', 'Beleg Strongbow', { faction: 'doriath', weapon: 'bow' }],
  ['huan', '훈', 'Huan the Hound', { faction: 'valinor', role: 'beast', weapon: 'none', base: 'L' }],
]},
{ sheet: 'roster-silmarillion-evil-v1.png', side: 'evil', units: [
  ['glaurung', '글라우룽', 'Glaurung', { faction: 'angband', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['carcharoth', '카르하로스', 'Carcharoth', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['gothmog_balrog', '고스모그(발록 군주)', 'Gothmog, Lord of Balrogs', { faction: 'angband', role: 'monster', weapon: 'whip', base: 'XXL' }],
  ['draugluin', '드라우글루인', 'Draugluin', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['thuringwethil', '수링웨실', 'Thuringwethil', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['boldog', '볼독', 'Boldog', { faction: 'angband', role: 'hero', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-hobbit-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['thorin', '토린 오큰실드', 'Thorin Oakenshield', { faction: 'dwarf', weapon: 'sword', base: 'L' }],
  ['tauriel', '타우리엘', 'Tauriel', { faction: 'elf', weapon: 'dagger' }],
  ['bard', '바드', 'Bard the Bowman', { faction: 'men', weapon: 'bow' }],
  ['dain', '데인', 'Dain Ironfoot', { faction: 'dwarf', weapon: 'mace', base: 'L' }],
  ['fili', '필리', 'Fili', { faction: 'dwarf', weapon: 'sword' }],
  ['kili', '킬리', 'Kili', { faction: 'dwarf', weapon: 'bow' }],
]},
{ sheet: 'roster-hobbit-evil-v1.png', side: 'evil', units: [
  ['azog', '아조그', 'Azog the Defiler', { faction: 'gundabad', role: 'hero', weapon: 'mace', base: 'L' }],
  ['azog_warg_rider', '아조그(흰 와르그)', 'Azog on white warg', { faction: 'gundabad', role: 'cavalry', weapon: 'mace', base: 'XL' }],
  ['necromancer', '네크로맨서', 'The Necromancer', { faction: 'dol_guldur', role: 'hero', weapon: 'staff', base: 'L' }],
  ['hunter_orc', '헌터 오크', 'Hunter Orc', { faction: 'gundabad', role: 'infantry', weapon: 'bow' }],
  ['gundabad_orc', '군다바드 오크', 'Gundabad Orc', { faction: 'gundabad', role: 'infantry', weapon: 'sword_shield' }],
  ['goblin_mercenary', '고블린 용병', 'Goblin Mercenary', { faction: 'moria', role: 'infantry', weapon: 'club' }],
]},
{ sheet: 'roster-exp-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['halbarad', '할바라드', 'Halbarad', { faction: 'arnor', weapon: 'banner', base: 'L' }],
  ['beregond', '베레곤드', 'Beregond', { faction: 'gondor', weapon: 'sword_shield' }],
  ['elladan', '엘라단', 'Elladan', { faction: 'rivendell', weapon: 'sword' }],
  ['elrohir', '엘로히르', 'Elrohir', { faction: 'rivendell', weapon: 'spear' }],
  ['grimbeorn', '그림베오른', 'Grimbeorn', { faction: 'beorning', weapon: 'axe', base: 'L' }],
  ['ghan_buri_ghan', '간부리간', 'Ghan-buri-Ghan', { faction: 'men', role: 'infantry', weapon: 'bow', base: 'S' }],
]},
{ sheet: 'roster-exp-evil-v1.png', side: 'evil', units: [
  ['suladan', '술라단', 'Suladan the Serpent Lord', { faction: 'harad', role: 'hero', weapon: 'spear', base: 'L' }],
  ['corsair_umbra', '움바르 해적', 'Corsair of Umbar', { faction: 'harad', role: 'infantry', weapon: 'sword' }],
  ['variag_horseman', '바리악 기수', 'Variag Horseman', { faction: 'rhun', role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['shagrat', '샤그랏', 'Shagrat', { faction: 'mordor', role: 'hero', weapon: 'sword_shield', base: 'L' }],
  ['gorbag', '고르바그', 'Gorbag', { faction: 'mordor', role: 'hero', weapon: 'sword' }],
  ['warg_alpha', '와르그 우두머리', 'Warg Alpha', { faction: 'isengard', role: 'beast', weapon: 'none', base: 'XL' }],
]},
{ sheet: 'roster-hobbit-company-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['balin', '발린', 'Balin', { role: 'hero', weapon: 'sword' }],
  ['dwalin', '드왈린', 'Dwalin', { role: 'hero', weapon: 'axe' }],
  ['gloin', '글로인', 'Gloin', { weapon: 'axe' }],
  ['oin', '오인', 'Oin', { weapon: 'club' }],
  ['nori', '노리', 'Nori', { weapon: 'sword' }],
  ['ori', '오리', 'Ori', { weapon: 'sword' }],
]},
{ sheet: 'roster-hobbit-exp-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['dori', '도리', 'Dori', { weapon: 'sword' }],
  ['bifur', '비푸르', 'Bifur', { weapon: 'spear' }],
  ['bofur', '보푸르', 'Bofur', { weapon: 'club' }],
  ['bombur', '봄부르', 'Bombur', { weapon: 'club' }],
  ['goat_rider', '산양 기수', 'Iron Hills Goat Rider', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['gollum', '골룸', 'Gollum', { side: 'evil', faction: 'moria', role: 'beast', weapon: 'none' }],
]},
{ sheet: 'roster-elf-exp-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['gil_galad', '길갈라드', 'Gil-galad', { faction: 'elf', weapon: 'spear', base: 'L' }],
  ['cirdan', '키르단', 'Cirdan the Shipwright', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['arwen', '아르웬', 'Arwen', { faction: 'rivendell', weapon: 'dagger' }],
  ['lindir', '린디르', 'Lindir', { faction: 'rivendell', weapon: 'sword' }],
  ['erestor', '에레스토르', 'Erestor', { faction: 'rivendell', weapon: 'sword' }],
  ['elf_seer', '엘프 선견자', 'Elf Seer', { faction: 'lothlorien', role: 'support', weapon: 'staff' }],
]},
{ sheet: 'roster-elf-exp-v2.png', side: 'good', role: 'infantry', base: 'M', units: [
  ['rumil', '루밀', 'Rumil', { faction: 'lothlorien', weapon: 'bow' }],
  ['orophin', '오로핀', 'Orophin', { faction: 'lothlorien', weapon: 'spear' }],
  ['mirkwood_sentinel', '미르크우드 보초', 'Mirkwood Sentinel', { faction: 'elf', weapon: 'pike' }],
  ['noldor_warrior', '놀도르 정예병', 'Noldor Warrior', { faction: 'elf', weapon: 'sword_shield', base: 'L' }],
  ['silvan_archer', '실반 궁수', 'Silvan Archer', { faction: 'elf', weapon: 'bow' }],
  ['elven_lancer', '엘프 기창기병', 'Elven Lancer', { faction: 'rivendell', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-mounted-heroes-v1.png', side: 'good', role: 'cavalry', base: 'XL', units: [
  ['imrahil_mounted', '임라힐(기마)', 'Prince Imrahil, mounted', { faction: 'gondor', weapon: 'lance' }],
  ['gandalf_mounted', '간달프(섀도우팩스)', 'Gandalf on Shadowfax', { faction: 'maiar', role: 'hero', weapon: 'sword' }],
  ['thranduil_mounted', '스란두일(기마)', 'Thranduil, mounted', { faction: 'elf', role: 'hero', weapon: 'sword' }],
  ['aragorn_mounted', '아라곤(기마)', 'Aragorn, mounted', { faction: 'gondor', role: 'hero', weapon: 'sword' }],
  ['theoden_mounted', '테오덴(기마)', 'Theoden, mounted', { faction: 'rohan', role: 'hero', weapon: 'sword' }],
  ['blackroot_archer', '검은뿌리골 궁수', 'Blackroot Vale Archer', { faction: 'gondor', role: 'infantry', weapon: 'bow', base: 'M' }],
]},
{ sheet: 'roster-mordor-monsters-v1.png', side: 'evil', units: [
  ['half_troll', '하프 트롤', 'Half-Troll of Far Harad', { faction: 'harad', role: 'monster', weapon: 'club', base: 'L' }],
  ['cave_drake', '동굴 드레이크', 'Cave Drake', { faction: 'moria', role: 'monster', weapon: 'none', base: 'XL' }],
  ['bat_swarm', '박쥐 떼', 'Bat Swarm', { faction: 'dol_guldur', role: 'monster', weapon: 'none' }],
  ['muzgur', '무즈구르', 'Muzgur, Morgul Shaman', { faction: 'angmar', role: 'hero', weapon: 'staff' }],
  ['buhrdur', '부르두르', 'Buhrdur, Troll Chieftain', { faction: 'angmar', role: 'monster', weapon: 'mace', base: 'XL' }],
  ['mahud_chieftain', '마후드 족장', 'Mahud War-Chieftain', { faction: 'harad', role: 'hero', weapon: 'spear', base: 'L' }],
]},
{ sheet: 'roster-west-heroes-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['eowyn_mounted', '에오윈(기마)', 'Eowyn, mounted', { faction: 'rohan', role: 'cavalry', weapon: 'sword', base: 'XL' }],
  ['forlong', '포를롱', 'Forlong the Fat', { faction: 'gondor', weapon: 'axe', base: 'L' }],
  ['erkenbrand', '에르켄브란트', 'Erkenbrand', { faction: 'rohan', weapon: 'sword_shield', base: 'L' }],
  ['damrod', '담로드', 'Damrod', { faction: 'gondor', weapon: 'bow' }],
  ['mablung', '마블룽', 'Mablung', { faction: 'gondor', weapon: 'sword' }],
  ['duinhir', '두인히르', 'Duinhir of Blackroot', { faction: 'gondor', weapon: 'bow' }],
]},
{ sheet: 'roster-east-monsters-v1.png', side: 'evil', units: [
  ['ugluk', '우글룩', 'Ugluk', { faction: 'isengard', role: 'hero', weapon: 'sword', base: 'L' }],
  ['mauhur', '마우후르', 'Mauhur', { faction: 'isengard', role: 'hero', weapon: 'sword' }],
  ['vrasku', '브라스쿠', 'Vrasku', { faction: 'isengard', role: 'hero', weapon: 'bow' }],
  ['stone_troll', '돌 트롤', 'Stone Troll', { faction: 'angmar', role: 'monster', weapon: 'club', base: 'XL' }],
  ['werewolf', '웨어울프', 'Werewolf', { faction: 'mordor', role: 'beast', weapon: 'none', base: 'L' }],
  ['gulavhar', '굴라브하르', 'Gulavhar, the Vampire', { faction: 'angmar', role: 'monster', weapon: 'none', base: 'XXL' }],
]},
{ sheet: 'terrain-objects-v3.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', units: [
  ['terr_catapult', '투석기', 'Field catapult'],
  ['terr_trebuchet', '트레뷰셋', 'Trebuchet'],
  ['terr_ballista', '발리스타', 'Ballista'],
  ['terr_grond', '그론드', 'GROND battering ram', { base: 'XXL' }],
  ['terr_siege_tower', '공성 탑', 'Siege tower', { base: 'L' }],
  ['terr_bomb', '폭파탄', 'Blasting bomb'],
]},
{ sheet: 'terrain-objects-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_rubble', '돌무더기', 'Rubble pile'],
  ['terr_broken_pillar', '부러진 기둥', 'Broken pillar'],
  ['terr_barricade', '목재 방벽', 'Wooden barricade'],
  ['terr_crates', '보급 상자', 'Supply crates'],
  ['terr_spike_line', '대기병 말뚝', 'Stake line'],
  ['terr_brazier', '화로', 'Brazier'],
]},
{ sheet: 'terrain-objects-v2.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_orc_totem', '오크 전리품 토템', 'Orcish totem'],
  ['terr_siege_ladder', '공성 사다리', 'Siege ladder'],
  ['terr_tent', '야영 텐트', 'Campaign tent'],
  ['terr_cart', '짐수레', 'Supply cart'],
  ['terr_campfire', '모닥불', 'Campfire'],
  ['terr_statue_head', '무너진 왕 석상', 'Toppled statue head', { base: 'L' }],
]},
{ sheet: 'terrain-natural-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'L', units: [
  ['terr_rock_outcrop', '바위 지형', 'Rock outcrop'],
  ['terr_standing_stones', '입석', 'Standing stones'],
  ['terr_pine_copse', '소나무 숲', 'Pine copse'],
  ['terr_oak_tree', '참나무', 'Old oak', { base: 'XL' }],
  ['terr_dead_tree', '고목', 'Dead tree'],
  ['terr_hedgerow', '울타리 덤불', 'Hedgerow'],
]},
{ sheet: 'terrain-structures-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'XL', units: [
  ['terr_ruined_wall', '무너진 성벽', 'Ruined wall'],
  ['terr_ruined_tower', '폐탑', 'Ruined tower'],
  ['terr_gondor_house', '곤도르 가옥', 'Gondor house'],
  ['terr_rohan_hall', '로한 회관', 'Rohan mead hall'],
  ['terr_orc_camp', '오크 야영지', 'Orc camp'],
  ['terr_barrow', '고분', 'Burial barrow'],
]},
{ sheet: 'roster-nazgul-nine-v1.png', side: 'evil', faction: 'angmar', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['dark_marshal', '어둠의 장군', 'The Dark Marshal'],
  ['shadow_lord', '그림자 군주', 'The Shadow Lord'],
  ['betrayer', '배신자', 'The Betrayer', { weapon: 'mace' }],
  ['tainted', '타락한 자', 'The Tainted', { weapon: 'dagger' }],
  ['undying', '죽지 않는 자', 'The Undying', { weapon: 'staff' }],
  ['knight_of_umbar', '움바르의 기사', 'Knight of Umbar', { faction: 'harad', weapon: 'spear' }],
]},
{ sheet: 'roster-good-fill-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['isildur', '이실두르', 'Isildur', { faction: 'gondor', weapon: 'sword', base: 'L' }],
  ['gandalf_white', '간달프(백색)', 'Gandalf the White', { faction: 'maiar', weapon: 'staff', base: 'L' }],
  ['denethor', '데네소르', 'Denethor, Steward of Gondor', { faction: 'gondor', weapon: 'none' }],
  ['huorn', '휘오른', 'Huorn', { faction: 'fangorn', role: 'monster', base: 'XL' }],
  ['boromir_mounted', '보로미르(기마)', 'Boromir, mounted', { faction: 'gondor', weapon: 'sword_shield', role: 'cavalry', base: 'XL' }],
  ['elrond_mounted', '엘론드(기마)', 'Elrond, mounted', { faction: 'rivendell', weapon: 'sword', role: 'cavalry', base: 'XL' }],
]},
{ sheet: 'roster-good-fill-v2.png', side: 'good', role: 'hero', base: 'L', units: [
  ['gandalf_white_mounted', '간달프 백색(기마)', 'Gandalf the White on Shadowfax', { faction: 'maiar', weapon: 'staff', role: 'cavalry', base: 'XL' }],
  ['theoden_foot', '세오덴(도보)', 'Theoden on foot', { faction: 'rohan', weapon: 'sword_shield' }],
  ['dain_boar', '다인(맷돼지)', 'Dain Ironfoot on war boar', { faction: 'dwarf', weapon: 'mace', role: 'cavalry', base: 'XL' }],
  ['faramir_mounted', '파라미르(기마)', 'Faramir, mounted', { faction: 'gondor', weapon: 'sword', role: 'cavalry', base: 'XL' }],
  ['eomer_foot', '에오메르(도보)', 'Eomer on foot', { faction: 'rohan', weapon: 'spear' }],
  ['elfhelm', '엘프헬름', 'Elfhelm of Rohan', { faction: 'rohan', weapon: 'sword_shield' }],
]},
{ sheet: 'roster-warg-riders-v1.png', side: 'evil', faction: 'isengard', role: 'cavalry', base: 'XL', units: [
  ['warg_rider_spear', '와르그 기병(창)', 'Warg Rider, spear', { weapon: 'spear' }],
  ['warg_rider_bow', '와르그 기병(활)', 'Warg Rider, bow', { weapon: 'bow' }],
  ['warg_chieftain', '와르그 우두머리 기병', 'Warg Chieftain', { role: 'hero', weapon: 'axe' }],
  ['wild_warg', '야생 와르그', 'Wild Warg', { role: 'monster', weapon: 'claws', base: 'L' }],
  ['wild_warg_alpha', '와르그 우두머리', 'Warg Alpha', { role: 'monster', weapon: 'claws', base: 'XL' }],
]},
{ sheet: 'single-ancalagon.png', side: 'evil', faction: 'angband', role: 'monster', weapon: 'claws', base: 'XXL', units: [
  ['ancalagon', '앙칼라곤', 'Ancalagon the Black'],
]},
{ sheet: 'terrain-objects-v4.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', units: [
  ['terr_ruined_gate', '무너진 관문', 'Ruined gate arch'],
  ['terr_wall_segment', '무너진 성벽 구간', 'Ruined wall segment'],
  ['terr_palisade', '목책', 'Wooden palisade'],
  ['terr_broken_stairs', '부서진 계단', 'Broken stairs'],
  ['terr_siege_wreck', '공성기 잔해', 'Wrecked siege engine'],
  ['terr_idol', '석상', 'Buried idol'],
]},
{ sheet: 'single-nazgul-fellbeast.png', side: 'evil', faction: 'angmar', role: 'monster', weapon: 'claws', base: 'XXL', units: [
  ['nazgul_fellbeast', '나즈굴(펠비스트)', 'Ringwraith on Fell Beast'],
]},
{ sheet: 'single-aragorn-blackgate.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['aragorn_blackgate', '아라곤(검은문)', 'Aragorn at the Black Gate'],
]},
{ sheet: 'single-aragorn-blackgate-mounted.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'XL', units: [
  ['aragorn_blackgate_mounted', '아라곤(검은문·기마)', 'Aragorn at the Black Gate, mounted'],
]},
];
