// Asset database source: one row per token PNG.
// Sheet blocks carry defaults (side/faction/role/base); per-unit entry = [id, ko, en, {overrides}].
// side: good | evil | terrain   role: hero | infantry | cavalry | monster | support | terrain
// base: S | M | L | XL | XXL   weapon: sword|sword_shield|spear|spear_shield|bow|crossbow|pike|twohanded|axe|mace|club|staff|banner|drum|dagger|bomb|torch|pitchfork|none|various
module.exports = [
{ sheet: 'lotr-tokens-v1.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['aragorn', '아라곤', 'Aragorn'],
  ['gandalf', '간달프', 'Gandalf the Grey', { faction: 'maiar', weapon: 'staff' }],
  ['warrior_minas_tirith', '미나스 티리스 전사', 'Warrior of Minas Tirith', { role: 'infantry', weapon: 'sword_shield', base: 'M' }],
  ['witchking_foot', '마술왕(도보)', 'Witch-king on foot', { traits: ['terror'], side: 'evil', faction: 'angmar', weapon: 'sword' }],
  ['orc_sword', '모르도르 오크(검)', 'Mordor Orc, sword', { side: 'evil', faction: 'mordor', role: 'infantry', base: 'S' }],
  ['cave_troll', '동굴 트롤', 'Cave Troll', { side: 'evil', faction: 'moria', role: 'monster', weapon: 'club', base: 'XXL' }],
]},
{ sheet: 'glorfindel-topdown-v2.png', side: 'good', faction: 'rivendell', role: 'hero', weapon: 'sword', units: [
  ['glorfindel_foot', '글로르핀델(도보)', 'Glorfindel on foot', { base: 'L' }],
  ['glorfindel_mounted', '글로르핀델(기마)', 'Glorfindel mounted', { role: 'hero', base: 'XL' }],
]},
{ sheet: 'fellbeast-topdown-v2.png', side: 'evil', faction: 'angmar', role: 'monster', base: 'XXL', units: [
  ['witchking_fellbeast', '마술왕(펠비스트)', 'Witch-king on Fell Beast', { traits: ['fly','terror'], weapon: 'sword' }],
]},
{ sheet: 'witchking-mounted-topdown-v1.png', side: 'evil', faction: 'angmar', role: 'cavalry', weapon: 'sword', base: 'XL', units: [
  ['witchking_mounted', '마술왕(기마)', 'Witch-king mounted', { role: 'hero', traits: ['terror'] }],
]},
{ sheet: 'roster-enemy-heroes-v1.png', side: 'evil', faction: 'mordor', role: 'hero', weapon: 'sword', units: [
  ['witchking_mounted_sheet', '마술왕(기마·예비)', 'Witch-king mounted (alt)', { role: 'hero', traits: ['terror'], faction: 'angmar', base: 'XL' }],
  ['witchking_foot_mace', '마술왕(철퇴)', 'Witch-king with mace', { traits: ['terror'], faction: 'angmar', weapon: 'mace', base: 'L' }],
  ['nazgul_sword', '나즈굴(검)', 'Nazgul, sword', { traits: ['terror'], faction: 'angmar', base: 'L' }],
  ['saruman', '사루만', 'Saruman the White', { faction: 'isengard', weapon: 'staff', base: 'L' }],
  ['orc_shaman', '오크 주술사', 'Orc Shaman', { faction: 'moria', role: 'support', weapon: 'staff', base: 'S' }],
  ['orc_captain', '오크 대장', 'Orc Captain', { base: 'M' }],
]},
{ sheet: 'roster-enemy-troops-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'S', units: [
  ['orc_spearman', '오크 창병', 'Orc Spearman', { weapon: 'spear' }],
  ['orc_archer', '오크 궁수', 'Orc Archer', { weapon: 'bow' }],
  ['uruk_swordshield', '우르크하이 검방', 'Uruk-hai, sword & shield', { faction: 'isengard', weapon: 'sword_shield', base: 'M' }],
  ['morannon_orc', '모라논 오크', 'Morannon Orc', { weapon: 'spear_shield', base: 'M' }],
  ['warg_rider', '와르그 기병', 'Warg Rider', { role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['haradrim_spearman', '하라드림 창병', 'Haradrim Spearman', { faction: 'harad', weapon: 'spear', base: 'M' }],
]},
{ sheet: 'roster-free-heroes-v1.png', side: 'good', role: 'hero', weapon: 'sword', units: [
  ['legolas', '레골라스', 'Legolas', { faction: 'elf', weapon: 'bow', base: 'M' }],
  ['gimli', '김리', 'Gimli', { faction: 'dwarf', weapon: 'axe', base: 'M' }],
  ['boromir', '보로미르', 'Boromir', { faction: 'gondor', weapon: 'sword_shield', base: 'L' }],
  ['eowyn', '에오윈', 'Eowyn', { faction: 'rohan', weapon: 'sword', base: 'M' }],
  ['frodo', '프로도', 'Frodo', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['elrond', '엘론드', 'Elrond', { faction: 'rivendell', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-free-troops-v1.png', side: 'good', role: 'infantry', base: 'M', units: [
  ['gondor_archer', '곤도르 궁수', 'Gondor Archer', { faction: 'gondor', weapon: 'bow' }],
  ['elf_swordsman', '엘프 검사', 'Elf Swordsman', { faction: 'elf', weapon: 'sword' }],
  ['dwarf_guardian', '드워프 가디언', 'Dwarf Guardian', { faction: 'dwarf', weapon: 'axe' }],
  ['rohan_royal_guard', '로한 근위병', 'Rohan Royal Guard', { faction: 'rohan', weapon: 'spear_shield' }],
  ['ithilien_ranger', '이틸리엔 레인저', 'Ithilien Ranger', { faction: 'gondor', weapon: 'bow' }],
  ['rohan_rider', '로한 기병', 'Rider of Rohan', { faction: 'rohan', role: 'cavalry', weapon: 'spear', base: 'XL' }],
]},
{ sheet: 'roster-monsters-v1.png', side: 'evil', role: 'monster', base: 'XXL', weapon: 'various', units: [
  ['balrog', '발록', 'Balrog of Moria', { traits: ['terror'], faction: 'moria' }],
  ['mountain_troll', '산악 트롤', 'Mountain Troll', { faction: 'mordor', weapon: 'club' }],
  ['shelob', '셀로브', 'Shelob', { traits: ['terror'], faction: 'mordor' }],
  ['barrow_wight', '고분 망령', 'Barrow-wight', { traits: ['terror'], faction: 'angmar', role: 'hero', weapon: 'sword', base: 'M' }],
  ['moria_goblin', '모리아 고블린', 'Moria Goblin', { faction: 'moria', role: 'infantry', weapon: 'sword', base: 'S' }],
  ['uruk_berserker', '우르크 광전사', 'Uruk-hai Berserker', { faction: 'isengard', role: 'infantry', weapon: 'twohanded', base: 'M' }],
]},
{ sheet: 'roster-sauron-nazgul-v1.png', side: 'evil', role: 'hero', base: 'L', units: [
  ['sauron', '사우론', 'Sauron', { traits: ['terror'], faction: 'mordor', role: 'monster', weapon: 'mace', base: 'XXL' }],
  ['nazgul_sword_2', '나즈굴(검·B)', 'Nazgul, sword (v2)', { traits: ['terror'], faction: 'angmar', weapon: 'sword' }],
  ['nazgul_mace', '나즈굴(철퇴)', 'Nazgul, mace', { traits: ['terror'], faction: 'angmar', weapon: 'mace' }],
  ['nazgul_mounted', '나즈굴(기마)', 'Nazgul mounted', { role: 'hero', traits: ['terror'], faction: 'angmar', weapon: 'sword', base: 'XL' }],
  ['morgul_knight', '모르굴 기사', 'Morgul Knight', { faction: 'mordor', role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['dwimmerlaik', '드위머레이크(갑옷 나즈굴)', 'Dwimmerlaik', { faction: 'angmar', weapon: 'mace' }],
]},
{ sheet: 'roster-minastirith-variants-v1.png', side: 'good', faction: 'gondor', role: 'infantry', base: 'M', units: [
  ['mt_swordshield', '미나스 티리스 검방', 'MT sword & shield', { weapon: 'sword_shield' }],
  ['mt_spear', '미나스 티리스 창병', 'MT spear', { weapon: 'spear' }],
  ['mt_spearshield', '미나스 티리스 창방', 'MT spear & shield', { weapon: 'spear_shield' }],
  ['mt_bowman', '미나스 티리스 궁수', 'MT bowman', { weapon: 'bow' }],
  ['mt_captain', '미나스 티리스 장교', 'MT shield captain', { role: 'hero', }],
  ['mt_fountain_guard', '샘물수위병', 'Fountain Court Guard', { weapon: 'spear_shield' }],
]},
{ sheet: 'roster-orc-variants-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'S', units: [
  ['orc_sword2', '오크(검)', 'Orc, sword', { weapon: 'sword' }],
  ['orc_swordshield', '오크(검방)', 'Orc, sword & shield', { weapon: 'sword_shield' }],
  ['orc_spear2', '오크(창)', 'Orc, spear', { weapon: 'spear' }],
  ['orc_twohanded', '오크(양손도끼)', 'Orc, two-handed axe', { weapon: 'twohanded' }],
  ['orc_bow', '오크(활)', 'Orc, bow', { weapon: 'bow' }],
  ['orc_drummer', '오크 전쟁북', 'Orc war drummer', { role: 'support', weapon: 'drum' }],
]},
{ sheet: 'roster-dwarf-variants-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['dwarf_axeshield', '드워프 도끼방', 'Dwarf, axe & shield', { weapon: 'axe' }],
  ['dwarf_2haxe', '드워프 양손도끼', 'Dwarf, two-handed axe', { weapon: 'twohanded' }],
  ['dwarf_ranger', '드워프 레인저', 'Dwarf Ranger', { weapon: 'bow' }],
  ['khazad_guard', '카자드 근위병', 'Khazad Guard', { weapon: 'axe' }],
  ['iron_guard', '아이언 가드', 'Iron Guard', { weapon: 'sword_shield' }],
  ['dwarf_banner', '드워프 기수', 'Dwarf banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-elf-variants-v1.png', side: 'good', faction: 'elf', role: 'infantry', base: 'M', units: [
  ['elf_swordshield', '엘프 검방', 'Elf, sword & shield', { weapon: 'sword_shield' }],
  ['elf_spear', '엘프 창병', 'Elf, spear', { weapon: 'spear' }],
  ['elf_bow', '엘프 궁수', 'Elf, bow', { weapon: 'bow' }],
  ['elf_glaive', '엘프 글레이브', 'Elf, glaive', { weapon: 'twohanded' }],
  ['galadhrim_warrior', '갈라드림 전사', 'Galadhrim Warrior', { faction: 'lothlorien', weapon: 'sword' }],
  ['elf_knight', '엘프 기마기사', 'Elf Knight', { faction: 'rivendell', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-uruk-variants-v1.png', side: 'evil', faction: 'isengard', role: 'infantry', base: 'M', units: [
  ['uruk_swordshield2', '우르크하이 검방', 'Uruk-hai, sword & shield', { weapon: 'sword_shield' }],
  ['uruk_pike', '우르크하이 파이크', 'Uruk-hai, pike', { weapon: 'pike' }],
  ['uruk_crossbow', '우르크하이 석궁', 'Uruk-hai, crossbow', { weapon: 'crossbow' }],
  ['uruk_scout', '우르크하이 스카웃', 'Uruk-hai Scout', { weapon: 'sword' }],
  ['uruk_berserker2', '우르크하이 광전사', 'Uruk-hai Berserker', { weapon: 'twohanded' }],
  ['uruk_banner', '우르크하이 기수', 'Uruk-hai banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-haradrim-easterling-v1.png', side: 'evil', role: 'infantry', base: 'M', units: [
  ['haradrim_spear', '하라드림 창병', 'Haradrim spearman', { faction: 'harad', weapon: 'spear' }],
  ['haradrim_bow', '하라드림 궁수', 'Haradrim archer', { faction: 'harad', weapon: 'bow' }],
  ['haradrim_priest', '하라드림 전사제', 'Haradrim warrior priest', { faction: 'harad', role: 'support', weapon: 'staff' }],
  ['easterling_phalanx', '이스터링 방진병', 'Easterling phalangite', { faction: 'easterling', weapon: 'pike' }],
  ['easterling_swordshield', '이스터링 검방', 'Easterling, sword & shield', { faction: 'easterling', weapon: 'sword_shield' }],
  ['easterling_kataphrakt', '이스터링 중기병', 'Easterling Kataphrakt', { faction: 'easterling', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-gondor-exp-v1.png', side: 'good', faction: 'gondor', role: 'infantry', base: 'M', units: [
  ['dol_amroth_knight', '돌 암로스 백조기사', 'Knight of Dol Amroth', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['gondor_knight', '곤도르 기병', 'Knight of Minas Tirith', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['osgiliath_veteran', '오스길리아스 베테랑', 'Osgiliath Veteran', { weapon: 'sword_shield' }],
  ['lossarnach_axeman', '로사르나흐 도끼병', 'Lossarnach Axeman', { weapon: 'twohanded' }],
  ['citadel_guard', '성채근위병', 'Citadel Guard', { weapon: 'spear_shield' }],
  ['pelennor_militia', '펠렌노르 민병', 'Pelennor Militia', { weapon: 'spear' }],
]},
{ sheet: 'roster-rohan-exp-v1.png', side: 'good', faction: 'rohan', role: 'infantry', base: 'M', units: [
  ['rohan_swordshield', '로한 검방', 'Rohan, sword & shield', { weapon: 'sword_shield' }],
  ['rohan_spear', '로한 창병', 'Rohan, spear', { weapon: 'spear' }],
  ['rohan_archer', '로한 궁수', 'Rohan archer', { weapon: 'bow' }],
  ['eomer', '에오메르(기마)', 'Eomer mounted', { role: 'hero', weapon: 'sword', base: 'XL' }],
  ['rohan_outrider', '로한 기마궁수', 'Rohan outrider', { role: 'cavalry', weapon: 'bow', base: 'XL' }],
  ['rohan_banner', '로한 기수', 'Rohan banner bearer', { role: 'support', weapon: 'banner' }],
]},
{ sheet: 'roster-mordor-elite-v1.png', side: 'evil', faction: 'mordor', role: 'infantry', base: 'M', units: [
  ['black_numenorean', '검은 누메노르인(도보)', 'Black Numenorean on foot', { weapon: 'sword_shield' }],
  ['black_numenorean_mounted', '검은 누메노르인(기마)', 'Black Numenorean mounted', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['orc_tracker', '오크 추적자', 'Orc Tracker', { weapon: 'twohanded', base: 'S' }],
  ['war_troll', '전쟁 트롤', 'Mordor War Troll', { role: 'monster', weapon: 'club', base: 'XXL' }],
  ['black_guard', '바라드두르 흑근위', 'Black Guard of Barad-dur', { weapon: 'spear_shield' }],
  ['orc_taskmaster', '오크 두목', 'Orc Taskmaster', { role: 'support', weapon: 'whip' }],
]},
{ sheet: 'roster-goblin-v1.png', side: 'evil', faction: 'moria', role: 'infantry', base: 'S', units: [
  ['goblin_spear', '고블린 창병', 'Goblin, spear', { weapon: 'spear' }],
  ['goblin_shield', '고블린 방패병', 'Goblin, shield', { weapon: 'sword_shield' }],
  ['goblin_bow', '고블린 궁수', 'Goblin, bow', { weapon: 'bow' }],
  ['goblin_prowler', '고블린 프라울러', 'Goblin Prowler', { weapon: 'dagger' }],
  ['goblin_king', '고블린 왕', 'Goblin King', { role: 'monster', weapon: 'club', base: 'L' }],
  ['goblin_shaman', '고블린 샤먼', 'Goblin Shaman', { role: 'support', weapon: 'staff' }],
]},
{ sheet: 'roster-isengard-exp-v1.png', side: 'evil', role: 'infantry', base: 'M', units: [
  ['dunlending_warrior', '던랜딩 전사', 'Dunlending Warrior', { faction: 'dunland', weapon: 'sword' }],
  ['dunlending_huscarl', '던랜딩 허스칼', 'Dunlending Huscarl', { faction: 'dunland', weapon: 'twohanded' }],
  ['warg', '야생 와르그', 'Wild Warg', { faction: 'isengard', role: 'monster', weapon: 'none' }],
  ['uruk_sapper', '우르크 폭파반', 'Uruk-hai Demolition Team', { faction: 'isengard', weapon: 'bomb' }],
  ['uruk_scout_archer', '우르크 스카웃 궁수', 'Uruk-hai Scout Archer', { faction: 'isengard', weapon: 'bow' }],
  ['crebain_swarm', '크레반 까마귀 떼', 'Crebain swarm', { traits: ['fly'], faction: 'isengard', role: 'support', weapon: 'none' }],
]},
{ sheet: 'roster-free-special-v1.png', side: 'good', base: 'M', units: [
  ['hobbit_shirriff', '호빗 민병', 'Hobbit Shirriff', { faction: 'shire', role: 'infantry', weapon: 'pitchfork', base: 'S' }],
  ['hobbit_bounder', '호빗 궁수', 'Hobbit Bounder', { faction: 'shire', role: 'infantry', weapon: 'bow', base: 'S' }],
  ['great_eagle', '대독수리', 'Great Eagle', { traits: ['fly'], faction: 'eagle', role: 'monster', weapon: 'none', base: 'XL' }],
  ['ent', '엔트', 'Ent', { faction: 'ent', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['beorning', '베오르닝 전사', 'Beorning', { faction: 'beorning', role: 'hero', weapon: 'axe', base: 'L' }],
  ['ranger_north', '북부 레인저', 'Ranger of the North', { faction: 'arnor', role: 'infantry', weapon: 'sword' }],
]},
{ sheet: 'roster-free-heroes-exp-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['theoden', '세오덴(기마)', 'Theoden mounted', { faction: 'rohan', role: 'cavalry', weapon: 'sword_shield', base: 'XL' }],
  ['faramir', '파라미르', 'Faramir', { faction: 'gondor', weapon: 'bow' }],
  ['haldir', '할디르', 'Haldir', { faction: 'lothlorien', weapon: 'twohanded' }],
  ['galadriel', '갈라드리엘', 'Galadriel', { faction: 'lothlorien', weapon: 'none' }],
  ['gamling', '감링(기수)', 'Gamling with banner', { faction: 'rohan', weapon: 'banner' }],
  ['samwise', '샘와이즈', 'Samwise Gamgee', { faction: 'shire', weapon: 'dagger', base: 'S' }],
]},
{ sheet: 'roster-evil-heroes-exp-v1.png', side: 'evil', role: 'hero', units: [
  ['mouth_of_sauron', '사우론의 입(기마)', 'Mouth of Sauron', { role: 'hero', faction: 'mordor', weapon: 'sword', base: 'XL' }],
  ['gothmog', '고스모그', 'Gothmog', { faction: 'mordor', weapon: 'mace', base: 'L' }],
  ['lurtz', '루르츠', 'Lurtz', { faction: 'isengard', weapon: 'bow', base: 'M' }],
  ['sharku', '샤르쿠(와르그)', 'Sharku on warg', { faction: 'isengard', role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['grima', '그리마 웜텅', 'Grima Wormtongue', { faction: 'isengard', weapon: 'dagger', base: 'M' }],
  ['khamul', '카물', 'Khamul the Easterling', { faction: 'angmar', weapon: 'mace', base: 'L' }],
]},
{ sheet: 'roster-legends-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['fingolfin', '핑골핀', 'Fingolfin', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['imrahil', '임라힐', 'Imrahil', { faction: 'gondor', weapon: 'lance' }],
  ['merry', '메리아독', 'Meriadoc Brandybuck', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['pippin', '피핀', 'Peregrin Took', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['beorn', '베오른', 'Beorn', { faction: 'beorning', weapon: 'twohanded', base: 'L' }],
  ['elendil', '엘렌딜', 'Elendil', { faction: 'arnor', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-legends-evil-v1.png', side: 'evil', units: [
  ['melkor', '멜코르', 'Melkor (Morgoth)', { faction: 'angband', role: 'monster', weapon: 'mace', base: 'XXL' }],
  ['mumakil', '무마킬', 'War Mumak', { traits: ['terror'], faction: 'harad', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['smaug', '스마우그', 'Smaug', { faction: 'erebor', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['ungoliant', '웅골리안트', 'Ungoliant', { faction: 'angband', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['bolg', '볼그', 'Bolg', { faction: 'gundabad', role: 'hero', weapon: 'mace', base: 'L' }],
  ['easterling_warlord', '이스터링 장군', 'Easterling Warlord', { faction: 'easterling', role: 'hero', weapon: 'pike' }],
]},
{ sheet: 'roster-legends-good-v2.png', side: 'good', role: 'hero', base: 'M', units: [
  ['radagast', '라다가스트', 'Radagast the Brown', { faction: 'maiar', weapon: 'staff' }],
  ['thranduil', '트란두일', 'Thranduil', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['celeborn', '켈레보른', 'Celeborn', { faction: 'lothlorien', weapon: 'spear' }],
  ['bilbo', '빌보', 'Bilbo Baggins', { faction: 'shire', weapon: 'dagger', base: 'S' }],
  ['king_of_the_dead', '망자의 왕', 'King of the Dead', { traits: ['terror'], faction: 'dead', weapon: 'sword', base: 'L' }],
  ['dead_soldier', '망자 병사', 'Soldier of the Dead', { traits: ['terror'], faction: 'dead', role: 'infantry', weapon: 'spear' }],
]},
{ sheet: 'roster-legends-evil-v2.png', side: 'evil', units: [
  ['olog_hai', '올로그하이', 'Olog-hai', { faction: 'mordor', role: 'monster', weapon: 'mace', base: 'XXL' }],
  ['watcher_in_the_water', '물 속의 감시자', 'Watcher in the Water', { traits: ['terror'], faction: 'moria', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['mirkwood_spider', '미르크우드 거미', 'Mirkwood Spider', { faction: 'dol_guldur', role: 'monster', weapon: 'none', base: 'L' }],
  ['harad_chieftain', '하라드 족장', 'Haradrim Chieftain', { faction: 'harad', role: 'hero', weapon: 'sword' }],
  ['uruk_captain', '우룩하이 대장', 'Uruk-hai Captain', { faction: 'isengard', role: 'hero', weapon: 'sword_shield', base: 'L' }],
  ['hill_troll', '언덕 트롤', 'Hill Troll', { faction: 'angmar', role: 'monster', weapon: 'club', base: 'XL' }],
]},
{ sheet: 'roster-silmarillion-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['feanor', '페아노르', 'Feanor', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['luthien', '루시엔', 'Luthien', { faction: 'doriath', weapon: 'staff' }],
  ['beren', '베렌', 'Beren', { faction: 'men', weapon: 'sword' }],
  ['turin', '투린', 'Turin Turambar', { faction: 'men', weapon: 'sword', base: 'L' }],
  ['beleg', '벨레그', 'Beleg Strongbow', { faction: 'doriath', weapon: 'bow' }],
  ['huan', '훈', 'Huan the Hound', { faction: 'valinor', role: 'beast', weapon: 'none', base: 'L' }],
]},
{ sheet: 'roster-silmarillion-evil-v1.png', side: 'evil', units: [
  ['glaurung', '글라우룽', 'Glaurung', { faction: 'angband', role: 'monster', weapon: 'none', base: 'XXL' }],
  ['carcharoth', '카르하로스', 'Carcharoth', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['gothmog_balrog', '고스모그(발록 군주)', 'Gothmog, Lord of Balrogs', { traits: ['terror'], faction: 'angband', role: 'monster', weapon: 'whip', base: 'XXL' }],
  ['draugluin', '드라우글루인', 'Draugluin', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['thuringwethil', '수링웨실', 'Thuringwethil', { faction: 'angband', role: 'monster', weapon: 'none', base: 'L' }],
  ['boldog', '볼독', 'Boldog', { faction: 'angband', role: 'hero', weapon: 'sword', base: 'L' }],
]},
{ sheet: 'roster-hobbit-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['thorin', '토린 오큰실드', 'Thorin Oakenshield', { faction: 'dwarf', weapon: 'sword', base: 'L' }],
  ['tauriel', '타우리엘', 'Tauriel', { faction: 'elf', weapon: 'dagger' }],
  ['bard', '바드', 'Bard the Bowman', { faction: 'men', weapon: 'bow' }],
  ['dain', '데인', 'Dain Ironfoot', { faction: 'dwarf', weapon: 'mace', base: 'L' }],
  ['fili', '필리', 'Fili', { faction: 'dwarf', weapon: 'sword' }],
  ['kili', '킬리', 'Kili', { faction: 'dwarf', weapon: 'bow' }],
]},
{ sheet: 'roster-hobbit-evil-v1.png', side: 'evil', units: [
  ['azog', '아조그', 'Azog the Defiler', { faction: 'gundabad', role: 'hero', weapon: 'mace', base: 'L' }],
  ['azog_warg_rider', '아조그(흰 와르그)', 'Azog on white warg', { faction: 'gundabad', role: 'cavalry', weapon: 'mace', base: 'XL' }],
  ['necromancer', '네크로맨서', 'The Necromancer', { faction: 'dol_guldur', role: 'hero', weapon: 'staff', base: 'L' }],
  ['hunter_orc', '헌터 오크', 'Hunter Orc', { faction: 'gundabad', role: 'infantry', weapon: 'bow' }],
  ['gundabad_orc', '군다바드 오크', 'Gundabad Orc', { faction: 'gundabad', role: 'infantry', weapon: 'sword_shield' }],
  ['goblin_mercenary', '고블린 용병', 'Goblin Mercenary', { faction: 'moria', role: 'infantry', weapon: 'club' }],
]},
{ sheet: 'roster-exp-good-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['halbarad', '할바라드', 'Halbarad', { faction: 'arnor', weapon: 'banner', base: 'L' }],
  ['beregond', '베레곤드', 'Beregond', { faction: 'gondor', weapon: 'sword_shield' }],
  ['elladan', '엘라단', 'Elladan', { faction: 'rivendell', weapon: 'sword' }],
  ['elrohir', '엘로히르', 'Elrohir', { faction: 'rivendell', weapon: 'spear' }],
  ['grimbeorn', '그림베오른', 'Grimbeorn', { faction: 'beorning', weapon: 'axe', base: 'L' }],
  ['ghan_buri_ghan', '간부리간', 'Ghan-buri-Ghan', { faction: 'men', role: 'infantry', weapon: 'bow', base: 'S' }],
]},
{ sheet: 'roster-exp-evil-v1.png', side: 'evil', units: [
  ['suladan', '술라단', 'Suladan the Serpent Lord', { faction: 'harad', role: 'hero', weapon: 'spear', base: 'L' }],
  ['corsair_umbra', '움바르 해적', 'Corsair of Umbar', { faction: 'harad', role: 'infantry', weapon: 'sword' }],
  ['variag_horseman', '바리악 기수', 'Variag Horseman', { faction: 'rhun', role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['shagrat', '샤그랏', 'Shagrat', { faction: 'mordor', role: 'hero', weapon: 'sword_shield', base: 'L' }],
  ['gorbag', '고르바그', 'Gorbag', { faction: 'mordor', role: 'hero', weapon: 'sword' }],
  ['warg_alpha', '와르그 우두머리', 'Warg Alpha', { faction: 'isengard', role: 'beast', weapon: 'none', base: 'XL' }],
]},
{ sheet: 'roster-hobbit-company-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['balin', '발린', 'Balin', { role: 'hero', weapon: 'sword' }],
  ['dwalin', '드왈린', 'Dwalin', { role: 'hero', weapon: 'axe' }],
  ['gloin', '글로인', 'Gloin', { weapon: 'axe' }],
  ['oin', '오인', 'Oin', { weapon: 'club' }],
  ['nori', '노리', 'Nori', { weapon: 'sword' }],
  ['ori', '오리', 'Ori', { weapon: 'sword' }],
]},
{ sheet: 'roster-hobbit-exp-v1.png', side: 'good', faction: 'dwarf', role: 'infantry', base: 'M', units: [
  ['dori', '도리', 'Dori', { weapon: 'sword' }],
  ['bifur', '비푸르', 'Bifur', { weapon: 'spear' }],
  ['bofur', '보푸르', 'Bofur', { weapon: 'club' }],
  ['bombur', '봄부르', 'Bombur', { weapon: 'club' }],
  ['goat_rider', '산양 기수', 'Iron Hills Goat Rider', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['gollum', '골룸', 'Gollum', { side: 'evil', faction: 'moria', role: 'beast', weapon: 'none' }],
]},
{ sheet: 'roster-elf-exp-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['gil_galad', '길갈라드', 'Gil-galad', { faction: 'elf', weapon: 'spear', base: 'L' }],
  ['cirdan', '키르단', 'Cirdan the Shipwright', { faction: 'elf', weapon: 'sword', base: 'L' }],
  ['arwen', '아르웬', 'Arwen', { faction: 'rivendell', weapon: 'dagger' }],
  ['lindir', '린디르', 'Lindir', { faction: 'rivendell', weapon: 'sword' }],
  ['erestor', '에레스토르', 'Erestor', { faction: 'rivendell', weapon: 'sword' }],
  ['elf_seer', '엘프 선견자', 'Elf Seer', { faction: 'lothlorien', role: 'support', weapon: 'staff' }],
]},
{ sheet: 'roster-elf-exp-v2.png', side: 'good', role: 'infantry', base: 'M', units: [
  ['rumil', '루밀', 'Rumil', { faction: 'lothlorien', role: 'hero', weapon: 'bow' }],
  ['orophin', '오로핀', 'Orophin', { faction: 'lothlorien', role: 'hero', weapon: 'spear' }],
  ['mirkwood_sentinel', '미르크우드 보초', 'Mirkwood Sentinel', { faction: 'elf', weapon: 'pike' }],
  ['noldor_warrior', '놀도르 정예병', 'Noldor Warrior', { faction: 'elf', weapon: 'sword_shield', base: 'L' }],
  ['silvan_archer', '실반 궁수', 'Silvan Archer', { faction: 'elf', weapon: 'bow' }],
  ['elven_lancer', '엘프 기창기병', 'Elven Lancer', { faction: 'rivendell', role: 'cavalry', weapon: 'lance', base: 'XL' }],
]},
{ sheet: 'roster-mounted-heroes-v1.png', side: 'good', role: 'cavalry', base: 'XL', units: [
  ['imrahil_mounted', '임라힐(기마)', 'Prince Imrahil, mounted', { faction: 'gondor', weapon: 'lance' }],
  ['gandalf_mounted', '간달프(섀도우팩스)', 'Gandalf on Shadowfax', { faction: 'maiar', role: 'hero', weapon: 'sword' }],
  ['thranduil_mounted', '스란두일(기마)', 'Thranduil, mounted', { faction: 'elf', role: 'hero', weapon: 'sword' }],
  ['aragorn_mounted', '아라곤(기마)', 'Aragorn, mounted', { faction: 'gondor', role: 'hero', weapon: 'sword' }],
  ['theoden_mounted', '테오덴(기마)', 'Theoden, mounted', { faction: 'rohan', role: 'hero', weapon: 'sword' }],
  ['blackroot_archer', '검은뿌리골 궁수', 'Blackroot Vale Archer', { faction: 'gondor', role: 'infantry', weapon: 'bow', base: 'M' }],
]},
{ sheet: 'roster-mordor-monsters-v1.png', side: 'evil', units: [
  ['half_troll', '하프 트롤', 'Half-Troll of Far Harad', { faction: 'harad', role: 'monster', weapon: 'club', base: 'L' }],
  ['cave_drake', '동굴 드레이크', 'Cave Drake', { faction: 'moria', role: 'monster', weapon: 'none', base: 'XL' }],
  ['bat_swarm', '박쥐 떼', 'Bat Swarm', { traits: ['fly'], faction: 'dol_guldur', role: 'monster', weapon: 'none' }],
  ['muzgur', '무즈구르', 'Muzgur, Morgul Shaman', { faction: 'angmar', role: 'hero', weapon: 'staff' }],
  ['buhrdur', '부르두르', 'Buhrdur, Troll Chieftain', { faction: 'angmar', role: 'monster', weapon: 'mace', base: 'XL' }],
  ['mahud_chieftain', '마후드 족장', 'Mahud War-Chieftain', { faction: 'harad', role: 'hero', weapon: 'spear', base: 'L' }],
]},
{ sheet: 'roster-west-heroes-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['eowyn_mounted', '에오윈(기마)', 'Eowyn, mounted', { faction: 'rohan', role: 'cavalry', weapon: 'sword', base: 'XL' }],
  ['forlong', '포를롱', 'Forlong the Fat', { faction: 'gondor', weapon: 'axe', base: 'L' }],
  ['erkenbrand', '에르켄브란트', 'Erkenbrand', { faction: 'rohan', weapon: 'sword_shield', base: 'L' }],
  ['damrod', '담로드', 'Damrod', { faction: 'gondor', weapon: 'bow' }],
  ['mablung', '마블룽', 'Mablung', { faction: 'gondor', weapon: 'sword' }],
  ['duinhir', '두인히르', 'Duinhir of Blackroot', { faction: 'gondor', weapon: 'bow' }],
]},
{ sheet: 'roster-east-monsters-v1.png', side: 'evil', units: [
  ['ugluk', '우글룩', 'Ugluk', { faction: 'isengard', role: 'hero', weapon: 'sword', base: 'L' }],
  ['mauhur', '마우후르', 'Mauhur', { faction: 'isengard', role: 'hero', weapon: 'sword' }],
  ['vrasku', '브라스쿠', 'Vrasku', { faction: 'isengard', role: 'hero', weapon: 'bow' }],
  ['stone_troll', '돌 트롤', 'Stone Troll', { faction: 'angmar', role: 'monster', weapon: 'club', base: 'XL' }],
  ['werewolf', '웨어울프', 'Werewolf', { traits: ['terror'], faction: 'mordor', role: 'beast', weapon: 'none', base: 'L' }],
  ['gulavhar', '굴라브하르', 'Gulavhar, the Vampire', { faction: 'angmar', role: 'monster', weapon: 'none', base: 'XXL' }],
]},
{ sheet: 'terrain-objects-v3.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', units: [
  ['terr_catapult', '투석기', 'Field catapult'],
  ['terr_trebuchet', '트레뷰셋', 'Trebuchet'],
  ['terr_ballista', '발리스타', 'Ballista'],
  ['terr_grond', '그론드', 'GROND battering ram', { base: 'XXL' }],
  ['terr_siege_tower', '공성 탑', 'Siege tower', { base: 'L' }],
  ['terr_bomb', '폭파탄', 'Blasting bomb'],
]},
{ sheet: 'terrain-objects-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_rubble', '돌무더기', 'Rubble pile'],
  ['terr_broken_pillar', '부러진 기둥', 'Broken pillar'],
  ['terr_barricade', '목재 방벽', 'Wooden barricade'],
  ['terr_crates', '보급 상자', 'Supply crates'],
  ['terr_spike_line', '대기병 말뚝', 'Stake line'],
  ['terr_brazier', '화로', 'Brazier'],
]},
{ sheet: 'terrain-objects-v2.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_orc_totem', '오크 전리품 토템', 'Orcish totem'],
  ['terr_siege_ladder', '공성 사다리', 'Siege ladder'],
  ['terr_tent', '야영 텐트', 'Campaign tent'],
  ['terr_cart', '짐수레', 'Supply cart'],
  ['terr_campfire', '모닥불', 'Campfire'],
  ['terr_statue_head', '무너진 왕 석상', 'Toppled statue head', { base: 'L' }],
]},
{ sheet: 'terrain-natural-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'L', units: [
  ['terr_rock_outcrop', '바위 지형', 'Rock outcrop'],
  ['terr_standing_stones', '입석', 'Standing stones'],
  ['terr_pine_copse', '소나무 숲', 'Pine copse'],
  ['terr_oak_tree', '참나무', 'Old oak', { base: 'XL' }],
  ['terr_dead_tree', '고목', 'Dead tree'],
  ['terr_hedgerow', '울타리 덤불', 'Hedgerow'],
]},
{ sheet: 'terrain-structures-v1.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'XL', units: [
  ['terr_ruined_wall', '무너진 성벽', 'Ruined wall'],
  ['terr_ruined_tower', '폐탑', 'Ruined tower'],
  ['terr_gondor_house', '곤도르 가옥', 'Gondor house'],
  ['terr_rohan_hall', '로한 회관', 'Rohan mead hall'],
  ['terr_orc_camp', '오크 야영지', 'Orc camp'],
  ['terr_barrow', '고분', 'Burial barrow'],
]},
{ sheet: 'roster-nazgul-nine-v1.png', side: 'evil', faction: 'angmar', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['dark_marshal', '어둠의 장군', 'The Dark Marshal'],
  ['shadow_lord', '그림자 군주', 'The Shadow Lord', { traits: ['terror'] }],
  ['betrayer', '배신자', 'The Betrayer', { weapon: 'mace' }],
  ['tainted', '타락한 자', 'The Tainted', { weapon: 'dagger' }],
  ['undying', '죽지 않는 자', 'The Undying', { weapon: 'staff' }],
  ['knight_of_umbar', '움바르의 기사', 'Knight of Umbar', { faction: 'harad', weapon: 'spear' }],
]},
{ sheet: 'roster-good-fill-v1.png', side: 'good', role: 'hero', base: 'M', units: [
  ['isildur', '이실두르', 'Isildur', { faction: 'gondor', weapon: 'sword', base: 'L' }],
  ['gandalf_white', '간달프(백색)', 'Gandalf the White', { faction: 'maiar', weapon: 'staff', base: 'L' }],
  ['denethor', '데네소르', 'Denethor, Steward of Gondor', { faction: 'gondor', weapon: 'none' }],
  ['huorn', '휘오른', 'Huorn', { faction: 'fangorn', role: 'monster', base: 'XL' }],
  ['boromir_mounted', '보로미르(기마)', 'Boromir, mounted', { faction: 'gondor', weapon: 'sword_shield', role: 'cavalry', base: 'XL' }],
  ['elrond_mounted', '엘론드(기마)', 'Elrond, mounted', { faction: 'rivendell', weapon: 'sword', role: 'cavalry', base: 'XL' }],
]},
{ sheet: 'roster-good-fill-v2.png', side: 'good', role: 'hero', base: 'L', units: [
  ['gandalf_white_mounted', '간달프 백색(기마)', 'Gandalf the White on Shadowfax', { faction: 'maiar', weapon: 'staff', role: 'cavalry', base: 'XL' }],
  ['theoden_foot', '세오덴(도보)', 'Theoden on foot', { faction: 'rohan', weapon: 'sword_shield' }],
  ['dain_boar', '다인(맷돼지)', 'Dain Ironfoot on war boar', { faction: 'dwarf', weapon: 'mace', role: 'cavalry', base: 'XL' }],
  ['faramir_mounted', '파라미르(기마)', 'Faramir, mounted', { faction: 'gondor', weapon: 'sword', role: 'cavalry', base: 'XL' }],
  ['eomer_foot', '에오메르(도보)', 'Eomer on foot', { faction: 'rohan', weapon: 'spear' }],
  ['elfhelm', '엘프헬름', 'Elfhelm of Rohan', { faction: 'rohan', weapon: 'sword_shield' }],
]},
{ sheet: 'roster-warg-riders-v1.png', side: 'evil', faction: 'isengard', role: 'cavalry', base: 'XL', units: [
  ['warg_rider_spear', '와르그 기병(창)', 'Warg Rider, spear', { weapon: 'spear' }],
  ['warg_rider_bow', '와르그 기병(활)', 'Warg Rider, bow', { weapon: 'bow' }],
  ['warg_chieftain', '와르그 우두머리 기병', 'Warg Chieftain', { role: 'hero', weapon: 'axe' }],
  ['wild_warg', '야생 와르그', 'Wild Warg', { role: 'monster', weapon: 'claws', base: 'L' }],
  ['wild_warg_alpha', '와르그 우두머리', 'Warg Alpha', { role: 'monster', weapon: 'claws', base: 'XL' }],
]},
{ sheet: 'single-ancalagon.png', side: 'evil', faction: 'angband', role: 'monster', weapon: 'claws', base: 'XXL', units: [
  ['ancalagon', '앙칼라곤', 'Ancalagon the Black'],
]},
{ sheet: 'terrain-objects-v4.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', units: [
  ['terr_ruined_gate', '무너진 관문', 'Ruined gate arch'],
  ['terr_wall_segment', '무너진 성벽 구간', 'Ruined wall segment'],
  ['terr_palisade', '목책', 'Wooden palisade'],
  ['terr_broken_stairs', '부서진 계단', 'Broken stairs'],
  ['terr_siege_wreck', '공성기 잔해', 'Wrecked siege engine'],
  ['terr_idol', '석상', 'Buried idol'],
]},
{ sheet: 'single-nazgul-fellbeast.png', side: 'evil', faction: 'angmar', role: 'monster', weapon: 'claws', base: 'XXL', units: [
  ['nazgul_fellbeast', '나즈굴(펠비스트)', 'Ringwraith on Fell Beast', { traits: ['fly','terror'] }],
]},
{ sheet: 'suladan-fellbeast.png', side: 'evil', faction: 'angmar', role: 'monster', weapon: 'claws', base: 'XXL', units: [
  ['fellbeast', '펠비스트', 'Fell Beast (riderless)', { traits: ['fly','terror'], weapon: 'claws' }],
]},
{ sheet: 'ents.png', side: 'good', faction: 'ent', role: 'monster', weapon: 'none', base: 'XXL', units: [
  ['quickbeam', '퀵빔', 'Quickbeam', { base: 'XL' }],
]},
{ sheet: 'single-aragorn-blackgate.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['aragorn_blackgate', '아라곤(검은문)', 'Aragorn at the Black Gate'],
]},
{ sheet: 'single-aragorn-blackgate-mounted.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'XL', units: [
  ['aragorn_blackgate_mounted', '아라곤(검은문·기마)', 'Aragorn at the Black Gate, mounted'],
]},


{ sheet: 'exp-gondor-heroes.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['anborn', '안보른', 'Anborn the Ranger', { weapon: 'bow', base: 'M' }],
  ['hirluin', '히를루인', 'Hirluin the Fair', { weapon: 'sword_shield' }],
  ['madril', '마드릴', 'Madril, Ranger Lieutenant', { weapon: 'sword', base: 'M' }],
  ['irolas', '이롤라스', 'Irolas, Guard of the Citadel', { weapon: 'sword_shield' }],
  ['hurin', '후린', 'Hurin, Warden of the Keys', { weapon: 'mace' }],
  ['cirion', '키리온', 'Cirion, Captain of Gondor', { weapon: 'sword' }],
]},
{ sheet: 'exp-rohan.png', side: 'good', faction: 'rohan', role: 'hero', weapon: 'sword', base: 'M', units: [
  ['theodred', '테오드레드', 'Theodred, Prince of Rohan'],
  ['hama', '하마', 'Hama, Doorwarden of Meduseld'],
  ['deorwine', '데오르바인', 'Deorwine, Chief of the Royal Guard'],
  ['grimbold', '그림볼드', 'Grimbold of Grimslade'],
  ['harding', '하딩', 'Harding of the Eastemnet', { weapon: 'bow' }],
  ['rohan_royal_guard_mounted', '로한 근위기병', 'Rohan Royal Guard, mounted', { role: 'cavalry', weapon: 'spear', base: 'XL' }],
]},
{ sheet: 'exp-numenor-arnor.png', side: 'good', faction: 'gondor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['arvedui', '아르베두이', 'Arvedui, Last King of Arnor', { faction: 'arnor' }],
  ['malbeth', '말베스', 'Malbeth the Seer', { role: 'hero', faction: 'arnor', weapon: 'staff', base: 'M' }],
  ['numenorean_captain', '누메노르 대장', 'Numenorean Captain'],
  ['numenorean_warrior', '누메노르 전사', 'Numenorean Warrior', { role: 'infantry', weapon: 'sword_shield', base: 'M' }],
  ['numenorean_spearman', '누메노르 창병', 'Numenorean Spearman', { role: 'infantry', weapon: 'spear', base: 'M' }],
  ['arnor_warrior', '아르노르 전사', 'Warrior of Arnor', { faction: 'arnor', role: 'infantry', weapon: 'sword_shield', base: 'M' }],
]},
{ sheet: 'exp-harad.png', side: 'evil', faction: 'harad', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['hasharin', '하샤린', 'Hasharin of Harad', { weapon: 'dagger', base: 'M' }],
  ['golden_king', '아브라칸의 황금왕', 'Golden King of Abrakhan'],
  ['mahud_beastmaster', '마후드 야수조련사', 'Mahud Beastmaster', { weapon: 'whip', base: 'M' }],
  ['watcher_karna', '카르나의 감시자', 'Watcher of Karna', { role: 'infantry', weapon: 'sword', base: 'M' }],
  ['haradrim_raider', '하라드림 습격기병', 'Haradrim Raider', { role: 'cavalry', weapon: 'spear', base: 'XL' }],
  ['mahud_camel_raider', '마후드 낙타기병', 'Mahud Camel Raider', { role: 'cavalry', weapon: 'spear', base: 'XL' }],
]},
{ sheet: 'exp-easterling.png', side: 'evil', faction: 'easterling', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['amdur', '암두르 검의 군주', 'Amdur, Lord of Blades'],
  ['dragon_knight', '드래곤 기사', 'Dragon Knight of Rhun', { role: 'cavalry', weapon: 'lance', base: 'XL' }],
  ['easterling_priest', '이스터링 전쟁사제', 'Easterling War Priest', { role: 'support', weapon: 'dagger', base: 'M' }],
  ['easterling_archer', '이스터링 궁수', 'Easterling Archer', { role: 'infantry', weapon: 'bow', base: 'M' }],
  ['variag_warrior', '바리악 전사', 'Variag Warrior of Khand', { role: 'infantry', weapon: 'sword_shield', base: 'M' }],
  ['khandish_horseman', '칸드 기병', 'Khandish Horseman', { role: 'cavalry', weapon: 'sword', base: 'XL' }],
]},
{ sheet: 'exp-dolguldur.png', side: 'evil', faction: 'mordor', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['forsaken', '버려진 자(나즈굴)', 'The Forsaken, Ringwraith', { faction: 'dol_guldur' }],
  ['castellan', '돌 굴두르 성주', 'Castellan of Dol Guldur', { faction: 'dol_guldur' }],
  ['dungeon_keeper', '감옥지기', 'Keeper of the Dungeons', { faction: 'dol_guldur', weapon: 'mace' }],
  ['kardush', '카두쉬 화염술사', 'Kardush the Firecaller', { role: 'support', weapon: 'staff', base: 'S' }],
  ['morgul_stalker', '모르굴 추적자', 'Morgul Stalker', { role: 'infantry', weapon: 'dagger', base: 'S' }],
  ['numenorean_marshal', '검은 누메노르 사령관', 'Black Numenorean Marshal', { weapon: 'mace' }],
]},
{ sheet: 'exp-dunland.png', side: 'evil', faction: 'dunland', role: 'hero', weapon: 'sword', base: 'L', units: [
  ['thrydan', '트리단 울프스베인', 'Thrydan Wolfsbane', { weapon: 'twohanded' }],
  ['gorulf', '고룰프 아이언스킨', 'Gorulf Ironskin', { weapon: 'axe', base: 'M' }],
  ['dunlending_berserker', '던랜드 광전사', 'Dunlending Berserker', { role: 'infantry', weapon: 'twohanded', base: 'M' }],
  ['dunlending_shaman', '던랜드 주술사', 'Dunlending Shaman', { role: 'support', weapon: 'staff', base: 'M' }],
  ['dunlending_archer', '던랜드 궁수', 'Dunlending Archer', { role: 'infantry', weapon: 'bow', base: 'M' }],
  ['ruffian', '샤키의 불한당', 'Sharkey’s Ruffian', { faction: 'isengard', role: 'infantry', weapon: 'club', base: 'M' }],
]},
{ sheet: 'exp-misc.png', side: 'good', faction: 'shire', role: 'hero', weapon: 'sword', base: 'S', units: [
  ['paladin_took', '팔라딘 툭', 'Paladin Took'],
  ['farmer_maggot', '농부 매곳', 'Farmer Maggot', { weapon: 'pitchfork' }],
  ['fredegar', '프레데가르 볼저', 'Fredegar Bolger', { weapon: 'dagger' }],
  ['durin_vi', '두린 6세', 'Durin VI, King of Khazad-dum', { faction: 'dwarf', weapon: 'mace', base: 'M' }],
  ['dead_spearman', '죽은자 창병', 'Dead spearman of Dunharrow', { traits: ['terror'], side: 'good', faction: 'dead', role: 'infantry', weapon: 'spear', base: 'M' }],
  ['stone_giant', '안개산맥 거인', 'Stone Giant of the Misty Mountains', { side: 'evil', faction: 'gundabad', role: 'monster', weapon: 'club', base: 'XXL' }],
]},


{ sheet: 'exp-wargs.png', side: 'evil', faction: 'gundabad', role: 'cavalry', weapon: 'spear', base: 'XL', units: [
  ['gundabad_warg_rider', '군다바드 와르그 기병', 'Gundabad Warg Rider'],
]},
{ sheet: 'terrain-fort.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'L', units: [
  ['terr_stone_barricade', '석재 바리케이드', 'Stone barricade'],
  ['terr_spike_barricade', '말뚝 바리케이드', 'Spiked barricade'],
  ['terr_orc_barricade', '오크 바리케이드', 'Orc barricade'],
  ['terr_sandbag', '모래주머니 진지', 'Sandbag emplacement'],
  ['terr_portcullis', '철창 성문', 'Portcullis'],
  ['terr_stone_archway', '석조 아치', 'Stone archway'],
]},
{ sheet: 'terrain-treasure.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_chest_open', '열린 보물상자', 'Open treasure chest'],
  ['terr_chest_closed', '보물상자', 'Treasure chest'],
  ['terr_gold_pile', '금화 더미', 'Pile of gold'],
  ['terr_relic_shrine', '유물 제단', 'Relic shrine', { base: 'L' }],
  ['terr_hoard', '보물 소굴', 'Treasure hoard', { base: 'L' }],
  ['terr_loot_bag', '전리품 가방', 'Loot satchel'],
]},
{ sheet: 'terrain-dungeon.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_sarcophagus', '석관', 'Sarcophagus', { base: 'L' }],
  ['terr_cage', '철창 우리', 'Prison cage', { base: 'L' }],
  ['terr_bone_pile', '뼈더미', 'Pile of bones'],
  ['terr_chain_post', '족쇄 기둥', 'Chain post'],
  ['terr_throne', '석조 왕좌', 'Stone throne', { base: 'L' }],
  ['terr_altar', '제단', 'Candlelit altar', { base: 'L' }],
]},
{ sheet: 'terrain-village.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_well', '우물', 'Stone well'],
  ['terr_market_stall', '장터 노점', 'Market stall', { base: 'L' }],
  ['terr_haystack', '건초더미', 'Haystack'],
  ['terr_hay_cart', '건초 수레', 'Hay cart'],
  ['terr_fence_gate', '울타리 문', 'Fence gate'],
  ['terr_beehive', '벌통', 'Beehive'],
]},
{ sheet: 'terrain-wild.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'L', units: [
  ['terr_boulders', '이끼 바위', 'Mossy boulders'],
  ['terr_mushroom_ring', '버섯 고리', 'Mushroom ring'],
  ['terr_bramble', '가시덤불', 'Thorny bramble'],
  ['terr_pond', '연못', 'Pond'],
  ['terr_waystone', '룬 이정석', 'Rune waystone'],
  ['terr_fallen_log', '쓰러진 통나무', 'Hollow fallen log'],
]},
{ sheet: 'terrain-camp.png', side: 'terrain', faction: 'terrain', role: 'terrain', weapon: 'none', base: 'M', units: [
  ['terr_war_banner', '전쟁기', 'War banner'],
  ['terr_weapon_rack', '무기 거치대', 'Weapon rack'],
  ['terr_anvil', '대장간 모루', 'Anvil with forge', { base: 'L' }],
  ['terr_ammo_pile', '화살 보급더미', 'Ammunition pile'],
  ['terr_map_table', '지도 탁자', 'Map table', { base: 'L' }],
  ['terr_torch_post', '횃불 기둥', 'Torch post'],
]},

{ sheet: 'nb-exp-heroes2.png', side: 'good', role: 'hero', base: 'M', units: [
  ['arathorn', '아라손', 'Arathorn II', { faction: 'arnor', weapon: 'sword' }],
  ['angbor', '앵보르 무서운 자', 'Angbor the Fearless', { faction: 'gondor', weapon: 'twohanded' }],
  ['dunhere', '둔헤레', 'Dunhere', { faction: 'rohan', weapon: 'spear' }],
  ['haleth', '할레스', 'Haleth son of Hama', { faction: 'rohan', weapon: 'spear' }],
  ['bandobras', '반도브라스 툭', 'Bandobras "Bullroarer" Took', { faction: 'shire', weapon: 'club', base: 'S' }],
  ['gildor', '길도르', 'Gildor Inglorion', { faction: 'rivendell', weapon: 'staff' }],
]},
{ sheet: 'nb-exp-evil2.png', side: 'evil', role: 'hero', base: 'M', units: [
  ['grishnakh', '그리쉬나크', 'Grishnakh', { faction: 'mordor', weapon: 'sword' }],
  ['snaga', '스나가', 'Snaga', { faction: 'isengard', weapon: 'sword', base: 'S' }],
  ['zagdush', '자그두쉬', 'Zagdush', { faction: 'moria', weapon: 'cleaver' }],
  ['dalamyr', '달라미르', 'Dalamyr, Fleetmaster of Umbar', { faction: 'umbar', weapon: 'twohanded' }],
  ['goblin_drummer', '고블린 북병', 'Goblin drummer', { faction: 'moria', role: 'support', weapon: 'none' }],
  ['yazneg', '야즈네그', 'Yazneg', { faction: 'gundabad', weapon: 'spear' }],
]},

{ sheet: 'nb-exp-heroes3.png', side: 'good', role: 'hero', weapon: 'sword', base: 'M', units: [
  ['eorl_the_young', '에오를', 'Eorl the Young', { faction: 'rohan', weapon: 'spear', base: 'XL' }],
  ['helm_hammerhand', '헬름 해머핸드', 'Helm Hammerhand', { faction: 'rohan', weapon: 'twohanded', base: 'L' }],
  ['tom_bombadil', '톰 봄바딜', 'Tom Bombadil', { faction: 'shire', weapon: 'none' }],
  ['goldberry', '골드베리', 'Goldberry', { faction: 'shire', weapon: 'none' }],
  ['dead_rider', '망자 기병', 'Rider of the Dead', { faction: 'dead', role: 'cavalry', weapon: 'spear', base: 'XL', traits: ['terror'] }],
  ['dervorin', '데르보린', 'Dervorin of Ringlo Vale', { faction: 'gondor' }],
]},
{ sheet: 'nb-exp-troops2.png', side: 'good', role: 'infantry', weapon: 'spear', base: 'M', units: [
  ['dol_amroth_man_at_arms', '돌 암로스 병사', 'Man-at-Arms of Dol Amroth', { faction: 'gondor' }],
  ['numenorean_archer', '누메노르 궁병', 'Numenorean archer', { faction: 'numenor', weapon: 'bow' }],
  ['sons_of_eorl', '에오를의 아들들', 'Sons of Eorl', { faction: 'rohan', role: 'cavalry', base: 'XL' }],
  ['vault_warden', '철언덕 방벽병', 'Iron Hills Vault Warden', { faction: 'dwarf' }],
  ['palace_guard', '궁정 근위병', 'Mirkwood Palace Guard', { faction: 'elf', weapon: 'sword' }],
  ['hobbit_militia', '호빗 민병대', 'Hobbit militia', { faction: 'shire', weapon: 'club', base: 'S' }],
]},
{ sheet: 'nb-exp-evil3.png', side: 'evil', role: 'hero', weapon: 'sword', base: 'M', units: [
  ['guritz', '구리츠', 'Guritz', { faction: 'mordor', weapon: 'twohanded' }],
  ['targsh', '타르그쉬', 'Targsh', { faction: 'isengard', weapon: 'spear' }],
  ['durburz', '두르부르즈', 'Durburz, Goblin King of Moria', { faction: 'moria' }],
  ['goblin_scribe', '고블린 서기', 'Goblin scribe', { faction: 'moria', role: 'support', weapon: 'none', base: 'S' }],
  ['fimbul', '핌불', 'Fimbul the Hunter', { faction: 'gundabad', weapon: 'spear' }],
  ['narzug', '나르주그', 'Narzug', { faction: 'gundabad', weapon: 'bow' }],
]},
{ sheet: 'nb-exp-harad2.png', side: 'evil', role: 'cavalry', weapon: 'none', base: 'XL', units: [
  ['khandish_chariot', '칸드 전차', 'Khandish chariot', { faction: 'easterling', weapon: 'bow' }],
  ['great_beast_gorgoroth', '고르고로스 거수', 'Great Beast of Gorgoroth', { faction: 'mordor', role: 'monster', base: 'XXL' }],
  ['khandish_chieftain', '칸드 족장', 'Khandish chieftain', { faction: 'easterling', role: 'hero', weapon: 'sword' }],
  ['abrakhan_guard', '아브라칸 근위대', 'Abrakhan Guard', { faction: 'harad', role: 'infantry', weapon: 'glaive', base: 'M' }],
  ['corsair_bosun', '코르사 갑판장', 'Corsair boatswain', { faction: 'umbar', role: 'infantry', weapon: 'sword', base: 'M' }],
  ['spider_queen', '거미 여왕', 'Spider Queen of Mirkwood', { faction: 'dol_guldur', role: 'monster', weapon: 'claws' }],
]},

  // --- 실마릴리온·스토리 확장 (48) ---
  { sheet:'px-nb-exp-silm1.png', side:'good', faction:'elf', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['turgon','투르곤','Turgon'],
    ['fingon','핑곤','Fingon'],
    ['ecthelion','엑텔리온','Ecthelion']] },
  { sheet:'px-nb-exp-silm1.png', side:'good', faction:'elf', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['finrod_felagund','핀로드 펠라군드','Finrod Felagund']] },
  { sheet:'px-nb-exp-silm1.png', side:'good', faction:'men', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['tuor','투오르','Tuor'],
    ['hurin_thalion','후린 탈리온','Hurin Thalion']] },
  { sheet:'px-nb-exp-silm2.png', side:'good', faction:'elf', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['maedhros','마이드로스','Maedhros'],
    ['celegorm','켈레고름','Celegorm']] },
  { sheet:'px-nb-exp-silm2.png', side:'good', faction:'doriath', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['thingol','싱골','Thingol'],
    ['mablung_sindar','마블룽','Mablung']] },
  { sheet:'px-nb-exp-silm2.png', side:'good', faction:'maiar', role:'hero', weapon:'staff', base:'M', traits:['terror'], units:[
    ['melian','멜리안','Melian']] },
  { sheet:'px-nb-exp-silm2.png', side:'good', faction:'dwarf', role:'hero', weapon:'dagger', base:'S', traits:[], units:[
    ['mim','밈','Mim the Petty-dwarf']] },
  { sheet:'px-nb-exp-silm3.png', side:'good', faction:'doriath', role:'infantry', weapon:'sword', base:'M', traits:[], units:[
    ['doriath_warrior','도리아스 전사','Doriath Warrior']] },
  { sheet:'px-nb-exp-silm3.png', side:'good', faction:'elf', role:'infantry', weapon:'bow', base:'M', traits:[], units:[
    ['falathrim_archer','팔라스림 궁수','Falathrim Archer'],
    ['nargothrond_ranger','나르고스론드 레인저','Nargothrond Ranger']] },
  { sheet:'px-nb-exp-silm3.png', side:'good', faction:'men', role:'infantry', weapon:'sword', base:'M', traits:[], units:[
    ['edain_warrior','에다인 전사','Edain Warrior']] },
  { sheet:'px-nb-exp-silm3.png', side:'good', faction:'elf', role:'infantry', weapon:'spear', base:'M', traits:[], units:[
    ['gondolin_guard','곤돌린 근위병','Gondolin Guard']] },
  { sheet:'px-nb-exp-silm3.png', side:'good', faction:'elf', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['mirkwood_captain','미르크우드 대장','Mirkwood Captain']] },
  { sheet:'px-nb-exp-mordor2.png', side:'evil', faction:'mordor', role:'infantry', weapon:'sword', base:'M', traits:[], units:[
    ['mordor_uruk','모르도르 우르크','Mordor Uruk']] },
  { sheet:'px-nb-exp-mordor2.png', side:'evil', faction:'mordor', role:'infantry', weapon:'sword', base:'M', traits:[], units:[
    ['morgul_orc','모르굴 오크','Morgul Orc']] },
  { sheet:'px-nb-exp-mordor2.png', side:'evil', faction:'mordor', role:'infantry', weapon:'dagger', base:'S', traits:[], units:[
    ['morgul_rat','모르굴 추적병','Morgul Rat']] },
  { sheet:'px-nb-exp-mordor2.png', side:'evil', faction:'mordor', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['ufthak','우프탁','Ufthak'],
    ['orc_sergeant','오크 하사','Orc Sergeant']] },
  { sheet:'px-nb-exp-mordor2.png', side:'evil', faction:'dol_guldur', role:'hero', weapon:'sword', base:'M', traits:['terror'], units:[
    ['ashrak','아슈라크','Ashrak']] },
  { sheet:'px-nb-exp-wotr.png', side:'evil', faction:'isengard', role:'monster', weapon:'club', base:'XL', traits:[], units:[
    ['isengard_troll','이센가드 트롤','Isengard Troll']] },
  { sheet:'px-nb-exp-wotr.png', side:'evil', faction:'dunland', role:'cavalry', weapon:'axe', base:'XL', traits:[], units:[
    ['dunlending_horseman','던랜드 기병','Dunlending Horseman']] },
  { sheet:'px-nb-exp-wotr.png', side:'evil', faction:'dunland', role:'hero', weapon:'twohanded', base:'M', traits:[], units:[
    ['wulf','울프','Wulf']] },
  { sheet:'px-nb-exp-wotr.png', side:'good', faction:'rohan', role:'hero', weapon:'axe', base:'M', traits:[], units:[
    ['hera','헤라','Hera'],
    ['frealaf','프레알라프','Frealaf']] },
  { sheet:'px-nb-exp-wotr.png', side:'good', faction:'rohan', role:'infantry', weapon:'spear', base:'M', traits:[], units:[
    ['rohan_yeoman','로한 여맨','Rohan Yeoman']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'harad', role:'infantry', weapon:'glaive', base:'M', traits:[], units:[
    ['serpent_guard','뱀 근위대','Serpent Guard']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'umbar', role:'infantry', weapon:'crossbow', base:'M', traits:[], units:[
    ['corsair_crossbowman','코르사 석궁병','Corsair Crossbowman']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'harad', role:'infantry', weapon:'blowpipe', base:'M', traits:[], units:[
    ['mahud_blowpipe','마후드 취관병','Mahud Blowpipe Warrior']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'easterling', role:'infantry', weapon:'mace', base:'M', traits:[], units:[
    ['khandish_warrior','칸드 전사','Khandish Warrior']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'easterling', role:'cavalry', weapon:'bow', base:'XL', traits:[], units:[
    ['easterling_mounted_archer','이스터링 기마궁수','Easterling Mounted Archer']] },
  { sheet:'px-nb-exp-harad3.png', side:'evil', faction:'harad', role:'hero', weapon:'spear', base:'M', traits:[], units:[
    ['far_harad_chieftain','먼 하라드 족장','Far Harad Chieftain']] },
  { sheet:'px-nb-exp-gondor2.png', side:'good', faction:'numenor', role:'cavalry', weapon:'lance', base:'XL', traits:[], units:[
    ['numenorean_knight','누메노르 기사','Numenorean Knight']] },
  { sheet:'px-nb-exp-gondor2.png', side:'good', faction:'arnor', role:'infantry', weapon:'bow', base:'M', traits:[], units:[
    ['arnor_archer','아르노르 궁수','Arnor Archer']] },
  { sheet:'px-nb-exp-gondor2.png', side:'good', faction:'gondor', role:'hero', weapon:'bow', base:'M', traits:[], units:[
    ['duilin','두일린','Duilin']] },
  { sheet:'px-nb-exp-gondor2.png', side:'good', faction:'gondor', role:'hero', weapon:'sword', base:'M', traits:[], units:[
    ['derufin','데루핀','Derufin'],
    ['hirgon','히르곤','Hirgon']] },
  { sheet:'px-nb-exp-gondor2.png', side:'good', faction:'gondor', role:'hero', weapon:'sword', base:'S', traits:[], units:[
    ['pippin_citadel','성채 근위병 피핀','Pippin, Guard of the Citadel']] },
  { sheet:'px-nb-exp-wild.png', side:'good', faction:'beorning', role:'monster', weapon:'claws', base:'XL', traits:[], units:[
    ['beorn_bear','베오른 (곰)','Beorn, Bear Form']] },
  { sheet:'px-nb-exp-wild.png', side:'good', faction:'eagle', role:'monster', weapon:'talons', base:'XL', traits:['fly'], units:[
    ['gwaihir','그와이히르','Gwaihir the Windlord']] },
  { sheet:'px-nb-exp-wild.png', side:'good', faction:'shire', role:'hero', weapon:'umbrella', base:'S', traits:[], units:[
    ['lobelia','로벨리아','Lobelia Sackville-Baggins'],
    ['will_whitfoot','윌 휫풋','Will Whitfoot']] },
  { sheet:'px-nb-exp-wild.png', side:'good', faction:'dwarf', role:'support', weapon:'shield', base:'M', traits:[], units:[
    ['dwarf_shieldbearers','드워프 방패 운반병','Dwarf Shieldbearers']] },
  { sheet:'px-nb-exp-wild.png', side:'good', faction:'dwarf', role:'hero', weapon:'mattock', base:'M', traits:[], units:[
    ['iron_hills_captain','아이언 힐즈 대장','Iron Hills Captain']] },
];
