// MESBG-style hero profiles keyed by unit id.
// f=Mobility(Fight→공격성등급) s=Strength d=Defence a=Attacks w=Wounds c=Courage
// might/will/fate = hero points; rules = signature special rules (MESBG army books)
module.exports = {
  // ===== Free Peoples =====
  aragorn:            { f: 6, s: 4, d: 6, a: 3, w: 3, c: 6, might: 3, will: 3, fate: 3, rules: ['Hero of Legend', 'Anduril Flame of the West'] },
  aragorn_mounted:    { f: 6, s: 4, d: 6, a: 3, w: 3, c: 6, might: 3, will: 3, fate: 3, rules: ['Hero of Legend', 'Anduril'] },
  aragorn_blackgate:  { f: 6, s: 4, d: 7, a: 3, w: 3, c: 7, might: 3, will: 3, fate: 3, rules: ['Hero of Legend', 'Anduril', 'King Elessar'] },
  aragorn_blackgate_mounted: { f: 6, s: 4, d: 7, a: 3, w: 3, c: 7, might: 3, will: 3, fate: 3, rules: ['Hero of Legend', 'Anduril', 'King Elessar'] },
  gandalf:            { f: 5, s: 3, d: 5, a: 1, w: 3, c: 7, might: 3, will: 20, fate: 3, rules: ['Istari', 'Glamdring'] },
  gandalf_mounted:    { f: 5, s: 3, d: 5, a: 1, w: 3, c: 7, might: 3, will: 20, fate: 3, rules: ['Istari', 'Glamdring', 'Shadowfax'] },
  gandalf_white:      { f: 5, s: 3, d: 6, a: 1, w: 3, c: 7, might: 3, will: 20, fate: 3, rules: ['Istari', 'Glamdring', 'The White Rider'] },
  legolas:            { f: 6, s: 3, d: 5, a: 2, w: 2, c: 4, might: 1, will: 1, fate: 1, rules: ['Deadly Shot', 'Elven Eyesight'] },
  gimli:              { f: 6, s: 4, d: 8, a: 2, w: 2, c: 6, might: 1, will: 0, fate: 2, rules: ['Dwarf', 'Champion of Erebor'] },
  boromir:            { f: 6, s: 4, d: 6, a: 3, w: 3, c: 6, might: 3, will: 1, fate: 2, rules: ['Horn of Gondor', 'Captain of the White Tower'] },
  eowyn:              { f: 4, s: 3, d: 4, a: 2, w: 2, c: 6, might: 2, will: 1, fate: 2, rules: ['Shieldmaiden of Rohan', 'I Am No Man'] },
  frodo:              { f: 3, s: 3, d: 5, a: 1, w: 2, c: 6, might: 1, will: 0, fate: 3, rules: ['Ring-bearer', 'Mithril Shirt', 'Sting'] },
  samwise:            { f: 3, s: 3, d: 4, a: 1, w: 2, c: 6, might: 1, will: 0, fate: 2, rules: ['Fellowship', 'Loyal Guardian'] },
  merry:              { f: 3, s: 3, d: 4, a: 1, w: 2, c: 5, might: 1, will: 0, fate: 2, rules: ['Esquire of Rohan'] },
  pippin:             { f: 3, s: 3, d: 4, a: 1, w: 2, c: 5, might: 1, will: 0, fate: 2, rules: ['Guard of the Citadel'] },
  elrond:             { f: 6, s: 4, d: 6, a: 3, w: 3, c: 7, might: 2, will: 10, fate: 3, rules: ['Lord of Rivendell', 'Vilya'] },
  glorfindel_foot:    { f: 7, s: 4, d: 6, a: 3, w: 3, c: 7, might: 2, will: 4, fate: 3, rules: ['Glorfindel', 'Elf-lord Reborn'] },
  glorfindel_mounted: { f: 7, s: 4, d: 6, a: 3, w: 3, c: 7, might: 2, will: 4, fate: 3, rules: ['Glorfindel', 'Asfaloth'] },
  galadriel:          { f: 6, s: 3, d: 4, a: 1, w: 3, c: 8, might: 2, will: 12, fate: 3, rules: ['Lady of Light', 'Nenya', 'Mirror of Galadriel'] },
  haldir:             { f: 5, s: 3, d: 5, a: 2, w: 2, c: 5, might: 1, will: 1, fate: 1, rules: ['Marchwarden of Lorien'] },
  faramir:            { f: 5, s: 4, d: 5, a: 2, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['Captain of the Rangers', 'Woodcraft'] },
  imrahil:            { f: 6, s: 4, d: 6, a: 2, w: 3, c: 6, might: 3, will: 1, fate: 2, rules: ['Prince of Dol Amroth', 'Swan Knight'] },
  denethor:           { f: 4, s: 3, d: 4, a: 1, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Steward of Gondor'] },
  isildur:            { f: 6, s: 4, d: 6, a: 3, w: 3, c: 5, might: 3, will: 1, fate: 2, rules: ['Ring-bearer', 'Doomed'] },
  elendil:            { f: 7, s: 5, d: 7, a: 3, w: 3, c: 7, might: 3, will: 2, fate: 3, rules: ['High King of Arnor', 'Narsil'] },
  gil_galad:          { f: 8, s: 5, d: 6, a: 4, w: 3, c: 8, might: 3, will: 3, fate: 3, rules: ['High King of the Noldor', 'Aeglos'] },
  cirdan:             { f: 6, s: 4, d: 5, a: 2, w: 3, c: 7, might: 2, will: 3, fate: 3, rules: ['Shipwright', 'Narya'] },
  arwen:              { f: 4, s: 3, d: 4, a: 1, w: 2, c: 5, might: 1, will: 1, fate: 1, rules: ['Evenstar'] },
  lindir:             { f: 4, s: 3, d: 4, a: 1, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Elf of Rivendell'] },
  erestor:            { f: 4, s: 3, d: 4, a: 1, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Elf of Rivendell'] },
  elladan:            { f: 6, s: 4, d: 5, a: 2, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['Sons of Elrond', 'Grey Company'] },
  elrohir:            { f: 6, s: 4, d: 5, a: 2, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['Sons of Elrond', 'Grey Company'] },
  rumil:              { f: 5, s: 3, d: 4, a: 2, w: 2, c: 5, might: 1, will: 0, fate: 1, rules: ['Lorien Archer'] },
  orophin:            { f: 5, s: 3, d: 4, a: 2, w: 2, c: 5, might: 1, will: 0, fate: 1, rules: ['Lorien Archer'] },
  thranduil:          { f: 6, s: 4, d: 5, a: 3, w: 3, c: 6, might: 3, will: 2, fate: 2, rules: ['Elvenking', 'Circlet of the Elvenking'] },
  thranduil_mounted:  { f: 6, s: 4, d: 5, a: 3, w: 3, c: 6, might: 3, will: 2, fate: 2, rules: ['Elvenking', 'Elk Mount'] },
  tauriel:            { f: 5, s: 3, d: 4, a: 2, w: 2, c: 5, might: 1, will: 1, fate: 1, rules: ['Captain of the Guard', 'Knives of Tauriel'] },
  celeborn:           { f: 7, s: 4, d: 6, a: 3, w: 3, c: 7, might: 2, will: 2, fate: 3, rules: ['Lord of Lothlorien'] },
  luthien:            { f: 4, s: 3, d: 4, a: 1, w: 2, c: 6, might: 2, will: 8, fate: 3, rules: ['Enchantress', 'Power of Song'] },
  beren:              { f: 5, s: 4, d: 5, a: 2, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['The One-handed'] },
  turin:              { f: 6, s: 4, d: 4, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Gurthang', 'Ill-fated'] },
  beleg:              { f: 5, s: 3, d: 4, a: 2, w: 2, c: 5, might: 1, will: 1, fate: 1, rules: ['Belthronding', 'Beleg Strongbow'] },
  fingolfin:          { f: 7, s: 5, d: 6, a: 4, w: 3, c: 7, might: 3, will: 2, fate: 3, rules: ['High King of the Noldor', 'Challenged Morgoth'] },
  feanor:             { f: 8, s: 5, d: 6, a: 4, w: 3, c: 7, might: 3, will: 3, fate: 3, rules: ['Greatest of the Noldor', 'Silmarils'] },
  beorn:              { f: 6, s: 4, d: 5, a: 3, w: 3, c: 6, might: 2, will: 1, fate: 3, rules: ['Skin-changer', 'Bear Form'] },
  beorning:           { f: 5, s: 4, d: 4, a: 2, w: 2, c: 5, might: 1, will: 0, fate: 1, rules: ['Beorning'] },
  grimbeorn:          { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 1, will: 1, fate: 1, rules: ['Beorning Chieftain'] },
  radagast:           { f: 5, s: 3, d: 4, a: 1, w: 3, c: 6, might: 2, will: 10, fate: 2, rules: ['Istari', 'Friend of Beasts'] },
  bilbo:              { f: 3, s: 3, d: 4, a: 1, w: 2, c: 5, might: 1, will: 0, fate: 2, rules: ['Ring-bearer', 'Sting'] },
  bard:               { f: 5, s: 4, d: 4, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 1, rules: ['Dragonslayer', 'Black Arrow'] },
  dain:               { f: 6, s: 4, d: 8, a: 3, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['Lord of the Iron Hills'] },
  thorin:             { f: 5, s: 4, d: 6, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Oakenshield', 'Thorin\'s Company'] },
  fili:               { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 1, fate: 1, rules: ['Thorin\'s Company'] },
  kili:               { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 1, fate: 1, rules: ['Thorin\'s Company'] },
  balin:              { f: 5, s: 4, d: 6, a: 2, w: 3, c: 5, might: 1, will: 1, fate: 1, rules: ['Thorin\'s Company', 'Lord of Moria'] },
  dwalin:             { f: 5, s: 4, d: 6, a: 3, w: 3, c: 5, might: 1, will: 1, fate: 1, rules: ['Thorin\'s Company', 'Dwalin\'s Axes'] },
  durin_vi:           { f: 6, s: 4, d: 7, a: 3, w: 3, c: 6, might: 2, will: 1, fate: 2, rules: ['King under the Mountain'] },
  arvedui:            { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Last King of Arnor'] },
  numenorean_captain: { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 1, will: 1, fate: 1, rules: ['Numenorean'] },
  numenorean_marshal: { f: 5, s: 4, d: 6, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 1, rules: ['Numenorean', 'Marshal'] },
  halbarad:           { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Grey Company', 'Standard of Arwen'] },
  beregond:           { f: 4, s: 4, d: 6, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Guard of the Citadel'] },
  madril:             { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Captain of Ithilien Rangers'] },
  damrod:             { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Ithilien Ranger'] },
  mablung:            { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Ithilien Ranger'] },
  anborn:             { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Ithilien Ranger'] },
  hirluin:            { f: 4, s: 4, d: 4, a: 2, w: 2, c: 5, might: 1, will: 0, fate: 1, rules: ['Lord of Pinnath Gelin'] },
  irolas:             { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Captain of the Guard'] },
  hurin:              { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Warden of the Keys'] },
  cirion:             { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Steward\'s Heir'] },
  forlong:            { f: 4, s: 4, d: 4, a: 3, w: 3, c: 5, might: 2, will: 0, fate: 1, rules: ['Lord of Lossarnach'] },
  erkenbrand:         { f: 5, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Marshal of the West-mark'] },
  duinhir:            { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Lord of Blackroot Vale'] },
  paladin_took:       { f: 3, s: 3, d: 4, a: 1, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Thain of the Shire'] },
  farmer_maggot:      { f: 3, s: 3, d: 4, a: 1, w: 2, c: 3, might: 0, will: 0, fate: 1, rules: ['Farmer', 'Dogs'] },
  fredegar:           { f: 3, s: 3, d: 4, a: 1, w: 2, c: 4, might: 0, will: 0, fate: 1, rules: ['Fatty Bolger'] },
  malbeth:            { f: 4, s: 3, d: 4, a: 1, w: 2, c: 6, might: 1, will: 3, fate: 2, rules: ['The Seer'] },

  // ===== Rohan =====
  theoden_foot:       { f: 5, s: 4, d: 6, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['King of Rohan', 'Herugrim'] },
  theoden_mounted:    { f: 5, s: 4, d: 6, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['King of Rohan', 'Herugrim', 'Snowmane'] },
  theodred:           { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Prince of Rohan'] },
  eomer:              { f: 6, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Marshal of the Riddermark', 'Guthwine'] },
  eomer_foot:         { f: 6, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Marshal of the Riddermark', 'Guthwine'] },
  gamling:            { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Royal Standard'] },
  hama:               { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Doorward of Meduseld'] },
  deorwine:           { f: 4, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 0, fate: 2, rules: ['Chief of the King\'s Knights'] },
  grimbold:           { f: 4, s: 3, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Marshal of the West-mark'] },
  harding:            { f: 4, s: 4, d: 5, a: 3, w: 2, c: 5, might: 2, will: 0, fate: 1, rules: ['Master of the Harrowfields'] },
  elfhelm:            { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Marshal of the East-mark'] },

  // ===== Evil =====
  witchking_foot:     { f: 6, s: 5, d: 7, a: 3, w: 3, c: 6, might: 3, will: 20, fate: 3, rules: ['Terror', 'The Morgul Lord', 'Black Breath'] },
  witchking_foot_mace:{ f: 6, s: 5, d: 7, a: 3, w: 3, c: 6, might: 3, will: 20, fate: 3, rules: ['Terror', 'The Morgul Lord', 'Mace of the Morgul Vale'] },
  witchking_mounted:  { f: 6, s: 5, d: 7, a: 3, w: 3, c: 6, might: 3, will: 20, fate: 3, rules: ['Terror', 'The Morgul Lord', 'Black Breath'] },
  witchking_mounted_sheet: { f: 6, s: 5, d: 7, a: 3, w: 3, c: 6, might: 3, will: 20, fate: 3, rules: ['Terror', 'The Morgul Lord'] },
  witchking_fellbeast:{ f: 6, s: 5, d: 7, a: 3, w: 3, c: 6, might: 3, will: 20, fate: 3, rules: ['Terror', 'The Morgul Lord', 'Fell Beast'] },
  nazgul_sword:       { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Unseen'] },
  nazgul_sword_2:     { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Unseen'] },
  nazgul_mace:        { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Unseen'] },
  nazgul_mounted:     { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Unseen'] },
  nazgul_fellbeast:   { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Fell Beast'] },
  dwimmerlaik:        { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Dwimmerlaik'] },
  khamul:             { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'Shadow of the East'] },
  dark_marshal:       { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Dark Marshal'] },
  shadow_lord:        { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Shadow Lord'] },
  betrayer:           { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Betrayer'] },
  tainted:            { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Tainted'] },
  undying:            { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Undying'] },
  muzgur:             { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 6, fate: 2, rules: ['Terror', 'Ringwraith', 'Muzgur'] },
  forsaken:           { f: 6, s: 4, d: 6, a: 2, w: 3, c: 6, might: 2, will: 8, fate: 2, rules: ['Terror', 'Ringwraith', 'The Forsaken'] },
  sauron:             { f: 9, s: 8, d: 9, a: 4, w: 4, c: 8, might: 4, will: 20, fate: 4, rules: ['The Dark Lord', 'Terror', 'Mace of Sauron'] },
  necromancer:        { f: 6, s: 5, d: 6, a: 2, w: 3, c: 7, might: 3, will: 20, fate: 3, rules: ['The Necromancer', 'Terror', 'Sauron in Disguise'] },
  saruman:            { f: 5, s: 4, d: 5, a: 1, w: 3, c: 6, might: 3, will: 12, fate: 3, rules: ['Istari', 'Voice of Saruman'] },
  mouth_of_sauron:    { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 2, will: 4, fate: 2, rules: ['Lieutenant of Barad-dur', 'Sorcerer'] },
  gothmog:            { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 2, will: 0, fate: 1, rules: ['Lieutenant of Morgul'] },
  gothmog_balrog:     { f: 7, s: 6, d: 8, a: 4, w: 4, c: 7, might: 3, will: 10, fate: 3, rules: ['Lord of Balrogs', 'Terror'] },
  balrog:             { f: 8, s: 6, d: 8, a: 4, w: 4, c: 7, might: 3, will: 10, fate: 3, rules: ['Durin\'s Bane', 'Terror', 'Whip of Flame'] },
  lurtz:              { f: 5, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['First of the Uruk-hai'] },
  ugluk:              { f: 4, s: 4, d: 4, a: 2, w: 3, c: 4, might: 1, will: 0, fate: 1, rules: ['Uruk-hai Scout Captain'] },
  mauhur:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Uruk-hai'] },
  vrasku:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Crossbow Captain'] },
  uruk_captain:       { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Uruk-hai Captain'] },
  grima:              { f: 2, s: 2, d: 3, a: 1, w: 1, c: 2, might: 1, will: 0, fate: 1, rules: ['Wormtongue', 'Spy'] },
  orc_captain:        { f: 3, s: 4, d: 4, a: 2, w: 2, c: 3, might: 1, will: 0, fate: 1, rules: ['Orc Captain'] },
  boldog:             { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Orc Hero'] },
  shagrat:            { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Captain of Cirith Ungol'] },
  gorbag:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Minas Morgul Garrison'] },
  barrow_wight:       { f: 5, s: 4, d: 5, a: 2, w: 2, c: 6, might: 2, will: 4, fate: 2, rules: ['Terror', 'Drain Will'] },
  king_of_the_dead:   { f: 5, s: 4, d: 6, a: 2, w: 3, c: 6, might: 2, will: 4, fate: 2, rules: ['Terror', 'Oathbreaker King'] },
  harad_chieftain:    { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Haradrim Chieftain'] },
  hasharin:           { f: 5, s: 4, d: 4, a: 3, w: 2, c: 6, might: 1, will: 0, fate: 1, rules: ['Assassin', 'Poisoned Blades'] },
  golden_king:        { f: 5, s: 4, d: 5, a: 2, w: 3, c: 5, might: 2, will: 1, fate: 1, rules: ['King of Abrakhan'] },
  mahud_chieftain:    { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Mahud Chief'] },
  mahud_beastmaster:  { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Beastmaster', 'Controls Mumak'] },
  amdur:              { f: 5, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Lord of Blades'] },
  suladan:            { f: 5, s: 4, d: 5, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Serpent Lord'] },
  easterling_warlord: { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Easterling Warlord'] },
  castellan:          { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Castellan of Dol Guldur'] },
  dungeon_keeper:     { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Keeper of the Dungeons'] },
  thrydan:            { f: 5, s: 4, d: 4, a: 3, w: 3, c: 5, might: 2, will: 0, fate: 1, rules: ['Chief of Dunland'] },
  gorulf:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Dunland Champion'] },
  warg_chieftain:     { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 0, fate: 1, rules: ['Warg-pack Leader'] },
  bolg:               { f: 6, s: 5, d: 6, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['Spawn of Azog'] },
  azog:               { f: 6, s: 5, d: 6, a: 3, w: 3, c: 5, might: 2, will: 1, fate: 2, rules: ['The Defiler', 'Pale Orc'] },

  // --- Silmarillion / 3rd-age expansion ---
  turgon:             { f: 7, s: 5, d: 7, a: 3, w: 3, c: 7, might: 3, will: 3, fate: 2, rules: ['King of Gondolin', 'Glamdring'] },
  fingon:             { f: 7, s: 5, d: 6, a: 3, w: 3, c: 7, might: 3, will: 2, fate: 2, rules: ['Valour of the Noldor'] },
  ecthelion:          { f: 7, s: 4, d: 6, a: 3, w: 3, c: 7, might: 3, will: 2, fate: 2, rules: ['Lord of the Fountain', 'Bane of Gothmog'] },
  finrod_felagund:    { f: 6, s: 4, d: 6, a: 3, w: 3, c: 7, might: 3, will: 3, fate: 2, rules: ['Felagund', 'Ring of Barahir'] },
  tuor:               { f: 6, s: 5, d: 6, a: 3, w: 3, c: 6, might: 3, will: 2, fate: 3, rules: ['Chosen of Ulmo'] },
  hurin_thalion:      { f: 6, s: 5, d: 6, a: 4, w: 3, c: 7, might: 2, will: 2, fate: 2, rules: ['Last Stand of Dor-lomin', 'Unyielding'] },
  maedhros:           { f: 7, s: 5, d: 6, a: 3, w: 3, c: 6, might: 3, will: 2, fate: 2, rules: ['Oath of Feanor', 'One-handed'] },
  celegorm:           { f: 7, s: 5, d: 6, a: 3, w: 3, c: 6, might: 3, will: 2, fate: 1, rules: ['Oath of Feanor', 'Master of Hounds'] },
  thingol:            { f: 7, s: 5, d: 7, a: 3, w: 3, c: 7, might: 3, will: 3, fate: 2, rules: ['Elu Thingol', 'King of Doriath'] },
  melian:             { f: 5, s: 3, d: 8, a: 2, w: 3, c: 7, might: 2, will: 4, fate: 3, rules: ['Girdle of Melian', 'Maia'] },
  mablung_sindar:     { f: 6, s: 4, d: 5, a: 3, w: 2, c: 6, might: 2, will: 2, fate: 1, rules: ['Chief of the March-wardens'] },
  mim:                { f: 3, s: 3, d: 4, a: 1, w: 2, c: 4, might: 1, will: 1, fate: 2, rules: ['Petty-dwarf', 'Grudge'] },
  mirkwood_captain:   { f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Woodland Realm'] },
  ufthak:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 1, will: 1, fate: 1, rules: ['Captured by Shelob'] },
  orc_sergeant:       { f: 4, s: 4, d: 4, a: 2, w: 2, c: 3, might: 1, will: 1, fate: 1, rules: ['Warband Leader'] },
  ashrak:             { f: 6, s: 4, d: 6, a: 3, w: 3, c: 6, might: 2, will: 2, fate: 1, rules: ['The Spider Knight', 'Terror'] },
  wulf:               { f: 5, s: 5, d: 5, a: 3, w: 3, c: 5, might: 3, will: 1, fate: 1, rules: ['Reclaimer of Edoras'] },
  hera:               { f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 2, fate: 2, rules: ['Shieldmaiden of the Wold'] },
  frealaf:            { f: 5, s: 5, d: 5, a: 3, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Avenger of Helm'] },
  duilin:             { f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Lord of Morthond', 'Dead-eye Shot'] },
  derufin:            { f: 5, s: 4, d: 6, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Son of Duinhir'] },
  hirgon:             { f: 5, s: 4, d: 5, a: 2, w: 2, c: 6, might: 2, will: 1, fate: 2, rules: ['Bearer of the Red Arrow'] },
  pippin_citadel:     { f: 4, s: 3, d: 5, a: 1, w: 2, c: 5, might: 1, will: 1, fate: 2, rules: ['Guard of the Citadel', 'Tookish Courage'] },
  far_harad_chieftain:{ f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Far Harad'] },
  iron_hills_captain: { f: 5, s: 5, d: 7, a: 2, w: 2, c: 6, might: 2, will: 1, fate: 1, rules: ['Iron Hills', 'Stubborn'] },
  lobelia:            { f: 2, s: 2, d: 3, a: 1, w: 1, c: 4, might: 1, will: 1, fate: 2, rules: ['Umbrella of Doom'] },
  will_whitfoot:      { f: 2, s: 2, d: 3, a: 1, w: 2, c: 4, might: 1, will: 1, fate: 2, rules: ['Mayor of Michel Delving'] },
  guritz:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 3, might: 1, will: 1, fate: 1, rules: ['Mordor Overseer'] },
  targsh:             { f: 5, s: 5, d: 5, a: 3, w: 3, c: 4, might: 2, will: 1, fate: 1, rules: ['Black Uruk Champion'] },
  durburz:            { f: 4, s: 4, d: 5, a: 2, w: 2, c: 4, might: 2, will: 1, fate: 1, rules: ['Goblin King of Moria'] },
  fimbul:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 2, will: 1, fate: 1, rules: ['Warg-rider Captain'] },
  narzug:             { f: 4, s: 4, d: 4, a: 2, w: 2, c: 4, might: 2, will: 1, fate: 1, rules: ['Hunter Captain'] },
  khandish_chieftain: { f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Chieftain of Khand'] },
  eorl_the_young:     { f: 6, s: 5, d: 6, a: 3, w: 3, c: 7, might: 3, will: 2, fate: 2, rules: ['First King of Rohan', 'Oath of Eorl'] },
  helm_hammerhand:    { f: 6, s: 6, d: 6, a: 4, w: 3, c: 6, might: 3, will: 2, fate: 2, rules: ['Hammerhand', 'Terror of Dunland'] },
  dervorin:           { f: 5, s: 4, d: 5, a: 2, w: 2, c: 5, might: 2, will: 1, fate: 1, rules: ['Lord of Ringlo Vale'] },
  tom_bombadil:       { f: 4, s: 2, d: 8, a: 2, w: 3, c: 8, might: 2, will: 4, fate: 3, rules: ['Master of the Old Forest', 'The Ring Has No Power Over Him'] },
  goldberry:          { f: 3, s: 2, d: 5, a: 1, w: 2, c: 6, might: 1, will: 3, fate: 2, rules: ['River-daughter'] },
};
