const fs=require('node:fs'),vm=require('node:vm');
module.exports=function(){const html=fs.readFileSync('LAST-WAR-BAND_v1.9.html','utf8'),store=new Map();
 const ctx={structuredClone,console,lt:(o,k,v)=>o[k]=v,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},window:{},document:{getElementById:()=>true}};vm.createContext(ctx);
 const section=(a,b)=>html.slice(html.indexOf(a),html.indexOf(b,html.indexOf(a)));
 vm.runInContext(section('window.__MESBG_ASSETS__=','</script>'),ctx);vm.runInContext(section('window.CAMPAIGN_META=','</script>'),ctx);vm.runInContext(section('/* LWB_TACTICS_BEGIN */','/* LWB_TACTICS_END */'),ctx);
 vm.runInContext('const '+section('Ht=Z=>','class Ve extends')+';const q=new ze(window.CAMPAIGN_META,123);class Ve{};let be=()=>null,He=()=>{};const UX={ready:false};',ctx);
 vm.runInContext(section('const CX = {','const oldPreload = Ve.prototype.preload'),ctx);
 vm.runInContext(section('const UNIT_RULES =',"if(!document.getElementById('tier-css'))"),ctx);vm.runInContext(section('const exactPlan=ve;','// A tap chooses a destination'),ctx);
 vm.runInContext(section('window.MESBG_EXTRA_UNITS=','const clarityGame = new Ot.Game(').split('/* LWB_UPGRADE_BEGIN */')[0],ctx);
 vm.runInContext(fs.readFileSync('runtime/upgrade.js','utf8').split('// Persistent preview')[0],ctx);
 vm.runInContext('this.api={q,P,CX,zt,UnitCatalog,He,Et,ve,chargePlan,Ue,baseFile,De,oe,Ne};',ctx);return {...ctx.api,store,assets:ctx.window.__MESBG_ASSETS__};};
