// Inlined into the existing game scope before Phaser starts.
const Tactics=window.LWBTactics,roleNames={infantry:'전열',support:'창 지원',archer:'사격',cavalry:'기병 돌격',monster:'괴수',hero:'영웅 지휘'},metaFor=id=>q.meta.get(id);
for(const def of window.LWB_TERRAIN_DEFS)q.meta.set(def.id,def);
const supportFor=(group,all=q.alive())=>Tactics.supportLinks(group,all,metaFor,(a,b)=>_t(a,b,q.terrain)==='clear');
supportAlly=function(u){const all=q.alive();for(const group of Oe(all)){const l=supportFor(group,all).find(l=>l.unit.uid===u.uid);if(l)return l.via;}return null;};
for(const [id,d] of Object.entries(UnitCatalog)){const m=d.meta,t=d.profile.traits,measured=window.LWB_BASES[id];if(measured)m.baseMm=measured;else if(!m.baseMm)m.baseMm=t.includes('monster')?60:t.includes('mounted')?40:25;q.meta.get(id).baseMm=m.baseMm;m.base=m.baseMm<=25?'M':m.baseMm<=40?'XL':'XXL';q.meta.get(id).base=m.base;}
const tacticalRound=P.beginRound;P.beginRound=function(){for(const u of this.units)u.supportSpent=false;return tacticalRound.call(this);};
const tacticalApply=P.applyCombat;P.applyCombat=function(r){for(const id of r.supports||[]){const u=this.unit(id);if(u)u.supportSpent=true;}for(const id of r.knockedDownUnits||[]){const u=this.unit(id);if(u)u.prone=true;}return tacticalApply.call(this,r);};
const tacticalHeroic=P.heroic;P.heroic=function(uid,key){const u=this.unit(uid);if(!u||!['move','shoot','fight'].includes(this.phase)||this.mode==='ai'&&this.side==='evil'&&this.phase!=='fight')return false;if(this.phase==='fight'&&!this.fightQueue.some(g=>g.includes(uid)))return false;return tacticalHeroic.call(this,uid,key);};
const tacticalDrain=P.drain;P.drain=function(){const e=tacticalDrain.call(this);return e.some(e=>e.result)?[...e.filter(e=>e.type!=='UnitKilled'),...e.filter(e=>e.type==='UnitKilled')]:e;};
be=function(b,u){
 if(b.engaged(u)||b.remaining(u)<12)return null;const all=b.alive(),foes=b.alive(Ht(u.side));if(!foes.length)return null;
 const meta=id=>b.meta.get(id),role=Tactics.role(u,meta),budget=b.remaining(u);if(role==='support'&&supportFor(Oe(all).flat(),all).some(l=>l.unit.uid===u.uid))return null;
 const score=p=>Tactics.positionScore(u,p,all,meta,b.mission==='defense'?Mt.objective:null,(a,v)=>_t(a,v,b.terrain)),options=[],reach=role==='archer'&&!u.moved?Math.min(budget,u.stats.move/2):budget;
 for(const amount of [reach,reach*.65,reach*.32])for(let i=0;i<16;i++){const a=i*Math.PI/8,p={x:u.x+Math.cos(a)*amount,y:u.y+Math.sin(a)*amount};if(Et(u,p,all,b.terrain))options.push({p,score:score(p)});}
 if(role==='support')for(const f of all.filter(v=>v.side===u.side&&v.uid!==u.uid&&!v.traits.includes('mounted')&&!v.traits.includes('monster'))){const e=foes.slice().sort((a,c)=>ht(f,a)-ht(f,c))[0],d=ht(f,e)||1,p={x:f.x+(f.x-e.x)/d*(u.radius+f.radius+1),y:f.y+(f.y-e.y)/d*(u.radius+f.radius+1)};if(Et(u,p,all,b.terrain))options.push({p,score:score(p)});}
 const current=score(u);for(const c of options.sort((a,b)=>a.score-b.score).slice(0,8)){if(c.score>=current-8)continue;const p=ve(u,c.p,all,b.terrain,budget,{snap:false});if(p&&p.distance>=12)return p.to;}return null;
};
He=function(b){
 const order={infantry:0,monster:1,hero:2,cavalry:3,support:4,archer:5},u=b.eligible().sort((a,c)=>order[Tactics.role(a,id=>b.meta.get(id))]-order[Tactics.role(c,id=>b.meta.get(id))])[0];if(!u){b.advance();return;}
 if(CX.skills[u.id]&&!b.skillReason(u)&&!b.engaged(u))b.skill(u.uid);if(!b.canAct(u))return;const role=Tactics.role(u,id=>b.meta.get(id));
 if(b.phase==='move'){if(!['archer','support'].includes(role)&&!b.engaged(u)){const value=v=>ht(u,v)+(role==='cavalry'?(v.traits.includes('mounted')?130:v.stats.shootRange?-100:0):0)+(role==='hero'?b.alive(u.side).filter(f=>Vt(f,v)).length*-90:0);for(const foe of b.alive(Ht(u.side)).sort((a,c)=>value(a)-value(c)).slice(0,5))if(b.charge(u.uid,foe.uid))return;}const dest=be(b,u);if(!dest||!b.move(u.uid,dest))b.wait(u.uid);}
 else if(b.phase==='shoot'){const target=b.validTargets(u).sort((a,c)=>a.currentWounds-c.currentWounds||ht(u,a)-ht(u,c))[0];if(!target||!b.shoot(u.uid,target.uid))b.wait(u.uid);}
};
const tacticalStage=P.stageInfo;P.stageInfo=function(n){const info=tacticalStage.call(this,n),theme=window.MESBG_STAGE_THEME[info.map],fallback=(theme?.foot||['orc_sword']).filter(id=>zt[id]);
 info.ids=info.ids.filter(id=>zt[id]&&this.meta.has(id)).map((id,i)=>{if(id===info.boss)return id;const p=zt[id];return n<4&&p.traits.includes('monster')||n<3&&p.traits.includes('mounted')?fallback[i%fallback.length]:id;});
 if(n>=3&&theme){const spear=(theme.spec||[]).find(id=>zt[id]&&Tactics.supportKind({id,traits:zt[id].traits},id=>this.meta.get(id)));if(spear)for(let i=3;i<info.ids.length;i+=5)if(info.ids[i]!==info.boss&&!zt[info.ids[i]].traits.includes('hero'))info.ids[i]=spear;}
 const counts={};for(const id of info.ids){const r=Tactics.role({id,traits:zt[id].traits,stats:zt[id]},id=>this.meta.get(id));counts[r]=(counts[r]||0)+1;}info.scouting=Object.entries(counts).map(([r,n])=>roleNames[r]+' '+n).join(' · ');return info;
};
const tacticalPrepare=P.prepareStage;P.prepareStage=function(){tacticalPrepare.call(this);const points=[[[650,840],[1680,850]],[[790,840],[1540,960]],[[480,950],[1780,780]]][(this.wave+this.mapIndex)%3];['terr_rock_outcrop','terr_ruined_wall'].forEach((id,i)=>{const t=this.terrain.find(t=>t.id===id);if(t){t.x=points[i][0];t.y=points[i][1];}});const id=this.mapIndex%2?'terr_crates':'terr_fallen_log';this.terrain.push({id,x:1165,y:850,w:150,h:105,kind:'cover',active:true});};
const tacticalSpawnEnemies=P.spawnEnemies;P.spawnEnemies=function(ids){const before=new Set(this.units.map(u=>u.uid));tacticalSpawnEnemies.call(this,ids);const added=this.alive('evil').filter(u=>!before.has(u.uid)),original=new Map(added.map(u=>[u.uid,{x:u.x,y:u.y}]));for(const u of added){u.x=-1000;u.y=-1000;}const order={infantry:0,monster:1,hero:2,support:3,archer:4,cavalry:5},count={};
 for(const u of added.sort((a,b)=>order[Tactics.role(a,metaFor)]-order[Tactics.role(b,metaFor)])){const r=Tactics.role(u,metaFor),i=count[r]||0;count[r]=i+1;const cols=[1165,1010,1320,855,1475,700,1630,545,1785],y=r==='archer'?1310:r==='support'?1190:r==='hero'?1160:r==='cavalry'?1040:1080,x=r==='cavalry'?(i%2?2060:270):cols[i%cols.length],candidates=[{x,y},original.get(u.uid)];for(let row=1320;row>=880;row-=85)for(const col of cols)candidates.push({x:col,y:row});const p=candidates.find(p=>Et(u,p,this.alive(),this.terrain));if(p)Object.assign(u,p);else{u.alive=false;this.delayed.push(u.id);}}
};
const tacticalSave=P.save;P.save=function(){tacticalSave.call(this);if(!['preparation','reward'].includes(this.phase))return;try{const raw=localStorage.getItem('mesbg-endless-save');if(!raw)return;const s=JSON.parse(raw);s.tactical={version:1,mapIndex:this.mapIndex,mission:this.mission,current:this.current,next:this.next,terrain:this.terrain};localStorage.setItem('mesbg-endless-save',JSON.stringify(s));}catch{this.emit('SaveFailed','저장 공간을 확인하세요. 현재 원정을 저장하지 못했습니다.');}};
const tacticalResume=P.resume;P.resume=function(){if(!tacticalResume.call(this))return false;const t=JSON.parse(localStorage.getItem('mesbg-endless-save'))?.tactical;if(t?.version===1){for(const k of ['mapIndex','mission','current','next'])if(t[k]!==undefined)this[k]=t[k];if(this.phase==='reward'&&Array.isArray(t.terrain))this.terrain=t.terrain;}else if(this.phase==='reward'){this.current=this.stageInfo(Math.max(1,this.wave));this.mapIndex=this.current.map;this.mission=this.current.mission;}for(const u of this.units){u.supportSpent=false;const m=this.meta.get(u.id);if(m)u.radius=m.baseMm*UNIT_RULES.worldPerMm/2;}return true;};
// Persistent preview shares the solver's support assignment.
field.insertAdjacentHTML('beforeend','<section id="fight-preview" class="hidden" aria-label="교전 참여자"><div class="fight-preview-title"></div><div class="fight-preview-units"></div></section><div id="tactical-legend" class="hidden">이동 범위 · 금색: 돌격 · 사선: 장애물</div>');
function previewGroup(){const all=q.alive(),groups=Oe(all);if(q.phase==='fight')return(q.fightQueue[0]||[]).map(id=>q.unit(id)).filter(u=>u?.alive);return groups.find(g=>g.some(u=>u.uid===q.selected)||supportFor(g,all).some(l=>l.unit.uid===q.selected))||[];}
function renderTacticalHUD(){const group=previewGroup(),box=ut('fight-preview');box.classList.toggle('hidden',!group.length||!['move','shoot','fight'].includes(q.phase)||inputBlocked());
 if(group.length){const links=supportFor(group),parts=group.map(u=>({u,label:'전열'})).concat(links.map(l=>({u:l.unit,label:l.rank===2?'파이크 2열':'창 지원'})));box.querySelector('.fight-preview-title').textContent='교전 '+group.filter(u=>u.side==='good').length+' vs '+group.filter(u=>u.side==='evil').length+' · 지원 '+links.filter(l=>l.unit.side==='good').length+' / '+links.filter(l=>l.unit.side==='evil').length;const key=parts.map(p=>p.u.uid+p.label).join('|');if(box.dataset.group!==key){box.dataset.group=key;box.querySelector('.fight-preview-units').innerHTML=parts.map(({u,label})=>'<button type="button" class="fight-member '+u.side+'" data-focus="'+u.uid+'" aria-label="'+esc(u.name+' · '+label)+'"><img src="'+Ut(q.meta.get(u.id).file)+'" alt=""><span>'+esc(u.name)+'</span><small>'+label+'</small></button>').join('');box.querySelectorAll('[data-focus]').forEach(el=>el.onclick=()=>{const u=q.unit(el.dataset.focus);if(u)setCamera(u.x,u.y,UX.zoom,'manual');});}}
 const u=actionableUnit();ut('tactical-legend').classList.toggle('hidden',q.phase!=='move'||!u||inputBlocked());if(u&&!UX.intent&&q.phase==='move')ut('dock-status').innerHTML=roleNames[Tactics.role(u,metaFor)]+' · 이동 <b>'+(q.remaining(u)/45).toFixed(1)+' / '+(u.stats.move/45).toFixed(1)+'″</b>'+(q.engaged(u)?' · 교전':u.stats.shootRange&&u.movementSpent*2>u.stats.move?' · 사격 불가':'');if(u)ut('dock-portrait').alt=u.name;
 const next=document.querySelector('.next-stage');if(next&&!next.querySelector('.scout-roles')){const p=document.createElement('p');p.className='scout-roles';p.textContent=q.stageInfo(q.wave+1).scouting;next.append(p);}
}
const tacticalRender=Yt;Yt=function(){tacticalRender();renderTacticalHUD();};
const tacticalRings=Ve.prototype.drawRings;Ve.prototype.drawRings=function(){tacticalRings.call(this);if(!this.rings||!UX.ready)return;const group=previewGroup(),g=this.rings,z=UX.zoom;for(const u of group){g.lineStyle(3/z,u.side==='good'?0xdbe3bd:0xda9475,1);g.strokeCircle(u.x,u.y,u.radius+8/z);}for(const l of supportFor(group)){g.lineStyle(3/z,0xdbc482,1);g.lineBetween(l.unit.x,l.unit.y,l.via.x,l.via.y);g.strokeCircle(l.unit.x,l.unit.y,l.unit.radius+5/z);}};
Ve.prototype.combat=async function(result){
 for(const hit of result.strikeResults.slice(0,qt>=20?2:18)){const u=this.b.unit(hit.attacker),v=this.b.unit(hit.target),a=this.tokens.get(hit.attacker),b=this.tokens.get(hit.target),s=a?.getByName('token'),victim=b?.getByName('token');if(!u||!v||!s||!victim)continue;
  const origin={x:a.x,y:a.y},dest={x:b.x,y:b.y},angle=Math.atan2(dest.y-origin.y,dest.x-origin.x),type=effectType(u,result.kind),sx=s.getData('baseSX')||s.scaleX,sy=s.getData('baseSY')||s.scaleY,center=s.getData('cxy')||{x:0,y:0};u.angle=Wt(u.id,origin,dest);await this.tween(s,{angle:s.angle+Ot.Math.Angle.ShortestBetween(s.angle,u.angle)},UX.reduced?1:85);
  const fx=this.add.image(dest.x,dest.y,'fx-'+type).setDepth(14).setDisplaySize(v.radius*2.4,v.radius*2.4).setRotation(angle).setAlpha(0),start=performance.now(),duration=UX.reduced?50:qt>=20?35:360/Math.min(qt,3);let impact=false;
  await new Promise(resolve=>{const frame=()=>{const t=Math.min(1,(performance.now()-start)/duration),m=window.TokenIdle.attackSample(type,t);if(!s.scene||!fx.scene){resolve();return;}if(!UX.reduced)s.setScale(sx*m.sx,sy*m.sy).setPosition(center.x+Math.cos(angle)*Math.sin(Math.PI*t)*10,center.y+Math.sin(angle)*Math.sin(Math.PI*t)*10);const life=Math.max(0,(t-.25)/.75);fx.setAlpha(t<.25?0:Math.sin(life*Math.PI));if(type==='shoot')fx.setPosition(origin.x+(dest.x-origin.x)*Math.min(1,life/.55),origin.y+(dest.y-origin.y)*Math.min(1,life/.55));if(t>=(type==='shoot'?.65:.46)&&!impact){impact=true;this.soundFX.play(type==='shoot'?'arrow_release':hit.wound?'sword_flesh':'sword_shield');if(hit.wound)victim.setTintFill(0xdfb498);if(!UX.reduced&&hit.wound&&(type==='smash'||hit.killed))this.cameras.main.shake(55,.0018);}if(t<1)requestAnimationFrame(frame);else resolve();};frame();});
  fx.destroy();s.setScale(sx,sy).setPosition(center.x,center.y);victim.clearTint();const label=this.add.text(dest.x,dest.y-v.radius-12,hit.prevented||(hit.wound?'−1':'Defense'),{fontFamily:'Pretendard',fontSize:'15px',color:hit.wound?'#ffcfac':'#e4dfcc',stroke:'#151913',strokeThickness:3}).setOrigin(.5).setDepth(15).setResolution(UX.dpr).setScale(1/UX.zoom);this.tween(label,{y:label.y-20,alpha:0},400).then(()=>label.destroy());if(hit.killed){await this.tween(victim,{alpha:0,y:victim.y+10},UX.reduced?1:160);b.setVisible(false);}
 }
 await Promise.all((result.pushVectors||[]).map(p=>{const c=this.tokens.get(p.uid);return c?this.tween(c,{x:p.to.x,y:p.to.y},160):Promise.resolve();}));
};
document.title='LAST WAR BAND · 전술 원정';window.MESBG.tactics={supportFor,role:u=>Tactics.role(u,metaFor),previewGroup,version:'2.0-review'};
